cmd/tk/debug.go
cmd/tk/jsonnet.go
cmd/tk/main.go
cmd/tk/workflow.go
go.mod
go.sum
pkg/jpath/jpath.go
pkg/jsonnet/jsonnet.go

:warning: **This PR should be reviewed with together with #7, because they are tightly coupled and some smaller changes (error handling) have been addressed in that one.** :warning: 
The `baseDir` is the most important directory, because it directly affects `JPATH`
resolution.
It was assumed as the `pwd` so far. However, it is handy in scripts to specify it
on the command line. This behaviour switches to specify only.
To fully support this, it was required to rework the configuration system, because we need to parse the CLI flags first, before we can read in the config, due to the `spec.json` residing inside of the `baseDir`.
⚠️ **BREAKING**: You must specify the `baseDir` on the command line. To mimic the old
behaviour, use `tk show .`
Closes #4

feat(cmd): allow the baseDir to be passed as an argument

---

cmd/tk/workflow.go
go.mod
pkg/config/v1alpha1/config.go
pkg/kubernetes/errors.go
pkg/kubernetes/kubectl.go
pkg/kubernetes/kubernetes.go
pkg/kubernetes/subsetdiff.go
pkg/kubernetes/subsetdiff_test.go
pkg/kubernetes/util.go
pkg/util/mapstr.go

So far, diffing was offloaded to kubectl. While this produces very nice results,
it is only possible for kubernetes version 1.13+.
Nevertheless, there are older cluster versions around, so these need to be
supported as well. subset-diff addresses those cases in the hopefully best way
possible.
To reduce field bloat, it only diffes those fields, that are present in the
local config. Kubernetes adds dynamic fields on the fly which we cannot know
about, so this is required.
Note: You WILL NOT see removed fields in the diff output. Upgrade your cluster
version to 1.13+ and use native diffing.

feat(kubernetes): subset-diff

---

pkg/kubernetes/kubernetes.go
pkg/kubernetes/subsetdiff.go
pkg/kubernetes/subsetdiff_test.go

version check was broken, now auto choose should work correctly
ignores apiVersion, too messy for now

fix(kubernetes/diff): check correctly & ignore apiVersion

---

cmd/tk/workflow.go
pkg/kubernetes/kubernetes.go

Use `-t=objectspec` to limit to an object.
Examples: 
```
-t=namespace/name
-t=deployment/asdf
```

feat(cli): limit output to specific objects only

---

cmd/tk/jsonnet.go
cmd/tk/main.go
cmd/tk/util.go
cmd/tk/workflow.go
pkg/kubernetes/kubectl.go
pkg/kubernetes/kubernetes.go
pkg/kubernetes/subsetdiff.go

improves the UX of especially the `diff` subcommand:
- uses systems pager for long outputs (`$PAGER`, fallback is `more`). Fixes #20 
- exits with `exit-code 16` in case of differences. Fixes #27 
- shows `diff` before `apply` (without pagination). Fixes #17

fix(cli): diff UX enhancements

---

pkg/kubernetes/subsetdiff.go

```
$ tk diff environments/cortex/eu-west2.dev/
Warning: `namespace` is deprecated, use `spec.namespace` instead.
Warning: `server` is deprecated, use `spec.apiServer` instead.
Warning: `team` is deprecated, use `metadata.labels.team` instead.
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x148b9d6]
goroutine 1 [running]:
github.com/grafana/tanka/pkg/kubernetes.Kubectl.SubsetDiff(0x0, 0x0, 0xc0000f6240, 0x15, 0xc00062c000, 0x918f, 0x9, 0xc0002e5e18, 0x8)
/Users/twilkie/Documents/src/github.com/sh0rez/tanka/pkg/kubernetes/subsetdiff.go:71 +0x7a6
github.com/grafana/tanka/pkg/kubernetes.(*Kubernetes).Diff(0xc0000b3380, 0xc000523000, 0x20, 0x20, 0x0, 0x0, 0x20) …
```

Nil pointer deference in subset diff.

---

cmd/tk/main.go

Due to some quirks of cobra, the new config format didn't actually work.
This fixes that.
Furthermore mutes the warnings about the deprecated config
Fixes #14

fix: config miss

---

cmd/tk/workflow.go
pkg/kubernetes/kubectl.go
pkg/kubernetes/kubernetes.go

`--dangerous-auto-approve`: Skip interactive change approval before apply, useful for
automation
`--force`: Force kubectl to apply, ignoring resource ownership
Fixes #32

feat(cli): autoApprove, forceApply

---

cmd/tk/util.go

- Don't paginate if content fits on one screen.
- Honor colors from less.
Stops output looking like:
```
ESC[1mESC[34mESC[40mdiff -u -N /var/folders/g5/3pb5_td927l61zm9xfmmtcp80000gn/T/diff017840273/LIVE-v1.ConfigMap.dev.consul /var/folders/g5/3pb5_td927l61zm9xfmmtcp80000gn/T/diff017840273/MERGED-v1.ConfigMap.dev.consul
ESC[0mESC[91mESC[40m--- /var/folders/g5/3pb5_td927l61zm9xfmmtcp80000gn/T/diff017840273/LIVE-v1.ConfigMap.dev.consul     2019-08-12 13:43:01.000000000 +0100
ESC[0mESC[92mESC[40m+++ /var/folders/g5/3pb5_td927l61zm9xfmmtcp80000gn/T/diff017840273/MERGED-v1.ConfigMap.dev.consul   2019-08-12 13:43:01.000000000 +0100
ESC[0mESC[1mESC[35mESC[40m@@ -1,7 +1,7 @@
ESC[0m apiVersion: v1
data:
```
Signed-off-by: Tom Wilkie <tom.wilkie@gmail.com>

Improve PAGER usage.

---

cmd/tk/main.go

Running `tk show` with no arguments would print the help text twice, like so:
```
Error: accepts 1 arg(s), received 0
Usage:
tk show [directory] [flags]
Flags:
-h, --help             help for show
-t, --target strings   only use the specified objects (Format: <type>/<name>)
Global Flags:
-v, --verbose
Error: accepts 1 arg(s), received 0
Usage:
tk show [directory] [flags]
Flags:
-h, --help             help for show
-t, --target strings   only use the specified objects (Format: <type>/<name>)
Global Flags:
-v, --verbose
Ouch: accepts 1 arg(s), received 0
```
This PR fixes the repeated output.

fix(cli): command executed twice on error

---

cmd/tk/workflow.go

feat(cli): abort `tk show` when stdout is being piped

---

pkg/jpath/jpath.go
pkg/kubernetes/errors.go
pkg/kubernetes/kubernetes.go

Although Tanka can `show` totally fine without a `spec.json`, however it panicked because of
the namespace override.
Now leaves the namespace untouched if it is not known.
Furthermore also fails on apply and diff without a `spec.json` with a clean error
message.
Fixes #55

fix(kubernetes): do not fail on nil receiver

---

Makefile

drops `standard-version` for determining the next version number, because it did
not work anyways.
Changelogs need to written by hand now as well, what we did before anyways.

chore(packaging): manual changelog + release

---

pkg/kubernetes/errors.go
pkg/kubernetes/kubectl.go
pkg/kubernetes/util.go

A more sophisticated approach on #59 than #60 took.
Uses a custom regex middleware for the stderr stream to mute all `exit status NUMBER` outputs from kubectl in diff mode, but retains all other outputs.
Furthermore fixes a minor bug in error handling where a missing object was always reported as a `secret`.
Fixes #59 
Closes #60

fix(kubernetes): correct handling of kubectl stderr

---

cmd/tk/util.go
pkg/kubernetes/subsetdiff.go

Diff used to output empty lines after the differences. Removes that.

fix(cli): remove empty lines on diff

---

cmd/tk/workflow.go
pkg/kubernetes/errors.go

Prints an error when the config is missing for an action that requires it
instead of just panicking.

fix(cli): error on missing config

---

cmd/tk/workflow.go
docs/targets.md
pkg/kubernetes/kubernetes.go

Switches target matching from literal string match to regexp.Match.
The `--target` / `-t` flag now takes a regular expression that is matched
against the literal string `<kind>/<name>`. If none of the expressions match,
the object is discarded.
To prevent substrings to match, the expressions is surrounded by
line anchors (`^%s$)`.
Fixes #53

feat(kubernetes): regexp targets

---

cmd/tk/workflow.go
pkg/kubernetes/kubernetes.go
pkg/kubernetes/util.go

Adds a `--summarize` / `-s` flag to `tk diff`, to automatically pipe the output
of `diff(1)` through `diffstat(1)` to generate a histogram of the changes, just
as git sometimes does.
**Result:**
```diff
extensions.v1beta1.DaemonSet.default.promtail                  |   97 +++
rbac.authorization.k8s.io.v1beta1.ClusterRole..promtail        |   20
rbac.authorization.k8s.io.v1beta1.ClusterRoleBinding..promtail |   15
v1.ConfigMap.default.promtail                                  |  260 ++++++++++
v1.Namespace..loki                                             |   12
v1.ServiceAccount.default.promtail                             |    8
6 files changed, 412 insertions(+)
```
Fixes #66

feat(kubernetes): diff histogram

---

.drone/drone.yml
.drone/release-note.md
Makefile

Gets `.drone/release-note.md` and `Makefile` in sync, so that copying the
download command actually works.

chore(packaging): fix binary name

---

docs/design/tanka.md
docs/environments.md
pkg/kubernetes/data_test.go
pkg/kubernetes/kubernetes.go
pkg/kubernetes/kubernetes_test.go
pkg/kubernetes/reconcile.go
pkg/kubernetes/reconcile_test.go

Adds unit tests for reconciliation phase to make sure it all works as expected (it didn't lol).
**Bugfixes / Features**:
- using a flat manifest led to an error
- it was not possible to specify the namespace from Jsonnet. It was overwritten by `spec.json`
**BREAKING**: `metadata.namespace` can now be set from Jsonnet by explicitly assigning a value to this property (This was the ksonnet behaviour). If left blank, the one from `spec.json` is used. **Make sure Jsonnet is not setting wrong namespaces**.

test(kubernetes): Reconciliation unit tests

---

cmd/tk/main.go

Adds another error context to make it clear to the user that the error relates
to `spec.json` and not the jsonnet.
Fixes #70

fix(cli): improve spec.json parse error

---

cmd/tk/env.go
cmd/tk/init.go
cmd/tk/jsonnet.go
cmd/tk/main.go
cmd/tk/util.go
cmd/tk/workflow.go
pkg/cmp/complete.go
pkg/config/v1alpha1/config.go
pkg/kubernetes/kubectl.go
pkg/util/alert.go

Adds a set of commands to work with and manipulate environments:
- `tk env add`: Create a new environment, optionally setting parameters (now also used by `tk init`)
- `tk env remove` (`tk env rm`): Remove an environment
- `tk env list` (`tk env ls`): List environments (optionally as JSON)
- `tk env set`: set properties on environments (the same available for `tk env add`)
These commands aim to be `ks env` compatible. However, Tanka infers the environments name from the directory, so it is not possible to modify it using `add` / `set` `--name`. Just `mv` the directory in that case (included in the error message).
Fixes #72

feat(cli): environment manipulation

---

CHANGELOG.md

Already releasing `0.5.0`, to have new `tk env` support included in binary builds.
This is more or less required for including Tanka in the Loki docs, so that users can use the new feature.

chore(release): v0.5.0

---

.drone/docker-manifest.tmpl

At the moment, the CI strips the leading `v` from the version tag, which means
`v0.5.0` would become `grafana/tanka:0.5.0`.
This behavior is not intuitive, changed it accordingly

chore(packaging): preserve full git tag for docker

---

cmd/tk/env.go

Fix panic when specify wrong env:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0xa732b5]
goroutine 1 [running]:
main.envSetCmd.func1(0xc00012a000, 0xc0004d2700, 0x1, 0x2)
/drone/src/cmd/tk/env.go:67 +0x115
github.com/spf13/cobra.(*Command).execute(0xc00012a000, 0xc00001e080, 0x2, 0x2, 0xc00012a000, 0xc00001e080)
/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:830 +0x2ae
github.com/spf13/cobra.(*Command).ExecuteC(0xc000020a00, 0xc000249780, 0xc000311860, 0x0)
/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914 +0x2fc
github.com/spf13/cobra.(*Command).Execute(...)
/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864
main.main()
/drone/src/cmd/tk/main.go:110 +0x48c
[root@test tanka]# …
```

fix(cli): panic on missing env

---

cmd/tk/env.go
cmd/tk/init.go
cmd/tk/main.go
pkg/kubernetes/kubernetes.go
pkg/kubernetes/kubernetes_test.go
pkg/spec/depreciations.go
pkg/spec/depreciations_test.go
pkg/spec/spec.go
pkg/spec/v1alpha1/config.go

Refactors the parsing of an environments `spec.json` into a separate package
`pkg/spec` to allow working with Tanka environments from outside of our
codebase.
A separate package was required because spec parsing also involves dealing with
deprecated ksonnet attributes and correctly setting constants and the
environments name, which would be too much logic to re-implement in every
project needing to parse our `spec.json`.

refactor(cli): spec parsing

---

docs/diff-strategy.md

Apparently, that throws the markdown renderer off. And, of course,
it's wrong.
Sorry for that typo in the previous PR.

doc: remove spurious blank in URL

---

.github/stale.yml

adds keepalive label to the stale bot. Furthermore reduces the stale limit to 30 days

chore(bot): stale keepalive

---

pkg/jsonnet/eval.go
pkg/jsonnet/importer.go
pkg/jsonnet/imports.go

Allows to directly import `.yaml` files from `.jsonnet`, as if they were JSON:
```jsonnet
local whatever = import "foo.yaml"
```

feat(jsonnet): import .yaml

---

README.md
docs/known-issues.md

You should start using ksonnet.beta.4 as 3 is going to not work soon anymore, with deployments being still in apps/v1beta2. The API group was deprecated and will be removed in the next Kubernetes version.

Use ksonnet.beta.4 in examples

---

docs/jsonnet/expected-structure.md
pkg/kubernetes/data_test.go
pkg/kubernetes/reconcile.go
pkg/kubernetes/reconcile_test.go

Adds array support for Reconcile.
Also documents the expected jsonnet structure. Fixes #110

feat(kubernetes): make reconcile support arrays

---

.drone/drone.jsonnet
.drone/drone.yml
Makefile

There is `drone-cli` (https://github.com/drone/drone-cli) which can take care of
building the `drone.yml` from Jsonnet.
This is more elegant than our previous `jsonnet | yq` dance.

chore(ci): bulid drone.yml using drone-cli

---

pkg/kubernetes/manifest/manifest.go
pkg/kubernetes/reconcile.go
pkg/kubernetes/subsetdiff.go

Due to faulty usage of json.Unmarshaller and errors the subsetdiff feature was
not working at all, but just overflowed the stack and made Tanka panic.
Resolves that (I think), had no time to do thorough testing)
/cc @malcolmholmes

fix(kubernetes): subsetdiff overflow

---

pkg/kubernetes/client/apply.go
pkg/kubernetes/client/client.go
pkg/kubernetes/client/diff.go
pkg/kubernetes/client/kubectl.go
pkg/kubernetes/kubernetes.go
pkg/kubernetes/subsetdiff.go
pkg/kubernetes/util/diff.go

Most cluster native operations won't succeed if the namespaces of the object is
yet to be created, even though it will be just created.
To enable a better user experience than kubectl does, let's do the following:
- on diff, just report every object in a missing object as entirely new
- on apply, create namespaces first to succeed in a single run (needed two before)

fix(kubernetes): properly handle missing namespaces

---

CHANGELOG.md

The last release is far too old anyways, let's release now and when the new big features are implemented (Secrets, Pruning, etc.) again!
Especially because of the Go API we need a tag to be able to import the module

doc(release): Changelog for 0.6.0

---

pkg/kubernetes/client/apply.go

If an environment doesn't define any namespaces, `tk apply` will fail with a "no objects passed to apply" error. This commit adds an extra check to only run that initial namespace apply if the filtered list of objects is non-empty.
Fixes #124.

kubernetes/client: only apply namespaces if there is a namespace object to apply

---

.drone/docker-manifest.tmpl
.drone/drone.yml
.drone/release-note.md

In #90 we broke docker tagging, because we instructed the template to leave the v prefix, drone docker removes.
This PR reverts the invalid change and adapts the release note, so it says `grafana/tanka:1.2.3`
Fixes https://github.com/grafana/tanka/issues/129

Unify docker tagging style

---

cmd/tk/workflow.go
pkg/kubernetes/kubernetes_test.go
pkg/kubernetes/reconcile.go
pkg/kubernetes/util/targetexp.go

was not before, but should be for better UX
Fixes #126

fix(cli): make -t case insensitive

---

cmd/tk/init.go

Use the jb cli instead of a declarative file for installing the packages. This
will work with all versions of jb, regardless of the jsonnetfile.json format

fix(cli): k8s init with older jb

---

pkg/kubernetes/reconcile.go
pkg/kubernetes/reconcile_test.go

While extracting the objects from the Jsonnet output, Tanka was not correctly
dealing with keys that were set to `nil`, leading those to be classified as
invalid objects, while they were no objects at all.
Such a case, where a key is explicitely set to `nil` is Jsonnet if:
```jsonnet
{
key: if false then "ouch"
}
```
Because the condition is false, Jsonnet adds an implicit `else null`.
Fixes #160

fix(kubernetes): ignore nil during reconcile

---

cmd/tk/env.go
pkg/kubernetes/client/context.go

Allows to set the `spec.apiServer` of an `Environment` using an already known
context:
```bash
$ tk env set environments/default --server-from-context eu-west1
```
The `--server-from-context` flag is autocompleted using data from `kubectl
config get-contexts`

feat(cli): set env server from context

---

cmd/tk/jsonnet.go
pkg/jsonnet/eval.go
pkg/jsonnet/importer.go
pkg/jsonnet/tk.libsonnet.go
pkg/spec/spec.go
pkg/tanka/parse.go

This change allows to use the parsed `spec.json` contents at runtime:
```jsonnet
local tk = import "tk";
{
env: tk.env,
}
```
It also introduces a Tanka native API extension (`import "tk"`), which serves as
a wrapper for all `std.extVar` and `std.nativeFunc` we use, so that we can make
breaking changes to those internals, without affecting the public API.
:warning: **There is a bug at the moment, that the `metadata.name` of the Environment is the CLI argument and not the actual name. This is fixed in #131 but not merged yet**
Fixes #161

feat(jsonnet): expose Environment at runtime

---

docs/docs/directory-structure.md
docs/doczrc.js

Adds a docs page about the directory structure used by Tanka. The page was lost during the docs rewrite, but still used by Tanka error messages, so we definitely need it
Fixes #164

docs: directory structure

---

pkg/jsonnet/importer.go

The current implementation of this feature broke support for using
`importstr`. While extending Jsonnet is nice, we must stay 100%
compatible, which we are not at the moment.

fix(jsonnet): disable import .yaml for importstr

---

cmd/tk/jsonnet.go
cmd/tk/workflow.go
pkg/tanka/parse.go
pkg/tanka/tanka.go

Adds two flags for working with extVars:
- `-e` / `--extCode`: Allows to bind any Jsonnet value (anything) to the
extVar. This flag is superior to `--extVar`, because it also handles
ints, bools, objects and arrays. **Strings need to be quoted**.
- `--extVar`: Only strings, but takes them unqouted. Added for
compatibility reasons to `jsonnet`.
Fixes #168 and Closes #171

feat(cli): extVars

---

cmd/tk/main.go
cmd/tk/tool.go
pkg/jsonnet/imports.go
pkg/jsonnet/imports_test.go
pkg/jsonnet/jpath/jpath.go
pkg/kubernetes/kubernetes_test.go
pkg/spec/spec.go
pkg/tanka/parse.go
pkg/tanka/tanka.go
pkg/tanka/workflow.go

Cherry-picks commits cbc2c66d3c8ca276e112b74fc6414448d4207576 and 8012c657f8dd7c7768eeb431d1c75c3d57698ea3 from #131, because they are a needed enhancement but the other PR is not going to be merged soon

fix: Stable environment name

---

pkg/kubernetes/data_test.go
pkg/kubernetes/kubernetes_test.go
pkg/kubernetes/reconcile.go
pkg/kubernetes/reconcile_test.go
pkg/kubernetes/testdata/k8s.libsonnet
pkg/kubernetes/testdata/resources.jsonnet
pkg/kubernetes/testdata/tdArray.jsonnet
pkg/kubernetes/testdata/tdDeep.jsonnet
pkg/kubernetes/testdata/tdFlat.jsonnet
pkg/kubernetes/testdata/tdInvalidPrimitive.jsonnet
pkg/kubernetes/testdata/tdRegular.jsonnet
pkg/kubernetes/testdata/utils.libsonnet

Moves the testdata for `pkg/kubernetes` out of Go, into several `.jsonnet` files for easier composing and reading (idea originally from @lawrencejones).
This also ensures that the data passed to `Extract()` and `Reconcile()` is exactly what would be used in real world. This is especially important because Go is usually typed, but `json.Unmarshal` returns untyped `interface{}` objects.
I also reverted a change from #166 (introducing `reflect`) that seemed required there, but as it turns out, this only happened because our testdata was written in Go instead of Jsonnet. Commit: f09257864c5bd94b3ec6526b72ef511c6403a7c4 /cc @jackatbancast

refactor(kubernetes): Jsonnet testdata

---

pkg/jsonnet/native/funcs.go
pkg/jsonnet/native/funcs_test.go
pkg/tanka/parse.go

- funcs.go was missing tests for the jsonnet native functions, this PR
adds some basic tests exercising some generic classses of arguments
- `parseYAML` seems to have been doing one extra step of marshalling the
YAML documents into JSON, which it probably shouldn't do and this PR
removes the functionality.
W.r.t. second point, the current implementation looks like
manifestJsonFrom Yaml or similar -- is there any use case for that that
would be worth adding it?

Add tests for jsonnet functions and fix parseYAML.

---

docs/docs/tutorial/jsonnet.mdx

The examples before and after use the namespace "monitoring" instead "my-namespace". Should be the same for consistency.

fix(docs): use namespace "monitoring" in jsonnet.mdx

---

docs/docs/directory-structure.md
docs/docs/libraries/import-paths.md
docs/docs/libraries/overriding.md
docs/doczrc.js
pkg/jsonnet/jpath/dirs_test.go
pkg/jsonnet/jpath/jpath.go
pkg/jsonnet/jpath/jpath_test.go

Introduces `tkrc.yaml` as an alternative project root marker to allow `jsonnetfile.json` per environment.
Also adds proper docs how to use this new environment local vendor feature.
Fixes #197

feat(jsonnet): Environment vendor

---

.drone/drone.jsonnet
.drone/drone.yml

Fetches tags in the release pipeline so the versions reported by `tk
--version` are actually semvers, not commit hashes
Also bumps the go version go 1.13

fix(release): fetch tags first

---

cmd/tk/util.go

**NOTE**: **Do not merge** until #202 is merged; for this to work correctly it depends on color sequences being applied per line rather than per diff chunk, which is introduced in #202. 
The `less` command has two flags: `--raw-control-chars` and `--RAW-CONTROL-CHARS`, each of which keeps ASCII control characters present in the paginated output. The former flag was being used previously, and the man page warns about various display problems occurring when using that flag.
On the other hand, `--RAW-CONTROL-CHARS` only keeps color escape sequences, and the man page notes that appearance will be maintained correctly in most cases. In my local testing, this appears to be true and colorized output in less will now work as expected.
Fixes #82.

fix(cli): paging issues with colored diff

---

pkg/kubernetes/client/apply.go
pkg/kubernetes/client/context.go
pkg/kubernetes/client/delete.go
pkg/kubernetes/client/diff.go
pkg/kubernetes/client/diff_test.go
pkg/kubernetes/client/exec.go
pkg/kubernetes/client/exec_test.go
pkg/kubernetes/client/get.go
pkg/kubernetes/client/kubectl.go
pkg/kubernetes/kubernetes.go
pkg/kubernetes/kubernetes_test.go
pkg/kubernetes/reconcile.go

Instead of naively setting the default namespaces on objects that don't
have one, we now overlay `$KUBECONFIG` with a patch to set the default
namespace on the context, so that `kubectl` will do the job for us.
`kubectl` does this far more intelligent than we did, especially it does
not inject the namespace on objects that don't take one.
Fixes #190 
There is one `TODO` left in injecting the patch into `$KUBECONFIG`: https://github.com/grafana/tanka/blob/0257f10a151d100ee7d645106ff76a8b71a4eae7/pkg/kubernetes/client/kubectl.go#L68-L72

fix(kubernetes): let kubectl handle namespaces

---

pkg/kubernetes/client/client.go
pkg/kubernetes/client/diff.go
pkg/kubernetes/client/kubectl.go
pkg/kubernetes/kubernetes.go

Properly handles `exit status 1` as a result from `kubectl diff`,
being aware of differences between `kubectl` versions:
* Before `1.18`:
* `0`: no error, no diff
* `1`: error or diff
* After 1.18 (https://github.com/kubernetes/kubernetes/pull/87437):
* `0`: no error, no diff
* `1`: diff
* `>1`: error
Fixes #204 
Fixes #205

fix(kubernetes): handle kubectl-diff exit 1

---

cmd/tk/export.go
cmd/tk/main.go
cmd/tk/workflow.go
docs/docs/exporting.md
pkg/tanka/workflow.go

Adds a new subcommand to Tanka for writing each resource in the `tk
show` output to a separate `.yaml` file
Fixes #206

feat(cli): Exporting

---

cmd/tk/util.go
cmd/tk/workflow.go
pkg/cli/colordiff.go
pkg/cli/colordiff_test.go
pkg/tanka/workflow.go

Lost that functionality somewhere during refactoring, but it really aids
readability, so we do need this.
Fixes #209

fix(cli): restore diff coloring on apply

---

pkg/kubernetes/client/context.go

This PR randomizes the file name used for `nsPatch`
Previously, in a multi user environment with a shared /tmp directory users would run into a problem if the `tk-kubectx-namespace.yaml` file was not cleaned up properly. If the file was created by a different user on the system, this would sometimes lead to tanka failing to create the file for another user.

fix(kubernetes): Randomize nsPatch file name

---

docs/docs/env-vars.md
docs/doczrc.js
pkg/kubernetes/client/context.go
pkg/kubernetes/client/delete.go
pkg/kubernetes/client/exec.go

Up to now, Tanka was using hard-coded string as a `kubectl` path, making
it hard to do any other tool without playing tricks with $PATH. This
commit allows to use TANKA_KUBECTL_PATH env variable to override the
path to `kubectl` used in Tanka's code.
See also https://github.com/grafana/tanka/issues/220 .

feat(cli): override kubectl path with env-var

---

docs/docs/targets.md

It makes absolutely no sense that `-t 'deployment/.*'` would result in `ClusterRole` ....

fix(docs): -t deployment example

---

pkg/tanka/workflow.go

If diff fails, it doesn't mean apply couldn't succeed anyways, so it is wrong to abort in such a case.
Changes that behavior so that the diff error is printed, but still continued to applying.
This does not fix the actual issue (diff failing for complex reasons), but makes Tanka still usable because after the first apply diff will most probably work again.

fix(kubernetes): ignore diff errs on apply

---

Dockerfile

Busybox less does not support `--RAW-CONTROL-CHARS`; `tk show` and `tk diff` fail in an unmodified alpine image.
Fixed by installing the full-fledged less.
**Before:**
```sh
> docker run -v `pwd`:/conf -w /conf -it grafana/tanka:latest show environments/dev
less: unrecognized option: RAW-CONTROL-CHARS
BusyBox v1.31.1 () multi-call binary.
Usage: less [-EFIMmNSRh~] [FILE]...
[...]
```

Fix 'tk show' and 'tk diff' in docker image

---

docs/docs/installation.md

Used `GOPATH` mode before, which had interesting side-effects (#233) that are not desired.
Fixes #233

fix(docs): use go modules in install guide

---

pkg/kubernetes/client/errors.go
pkg/kubernetes/kubernetes.go

Apparently you can't `%s` `type string` things that implement `Error()`,
as it recurses.
Fixes #238 
/cc @rfratto @malcolmholmes

fix(kubernetes): fmt related stack overflow

---

pkg/kubernetes/client/context.go
pkg/kubernetes/client/exec.go
pkg/kubernetes/client/kubectl.go

Don't call kubectl at all until after we drop the kubeconfig patch.
And use the correct os specific path separator.

Fixes for compatibility with windows style path environment variable.

---

Dockerfile

Adds several dependencies to the `Dockerfile`, so that Tanka can be
actuall used from there:
- `kubectl`, using the offical binary download
- `jsonnet-bundler`, compiling from source
- `less`, `git` and `diff` using alpine packages
Fixes #218

feat: more complete Dockerfile

---

pkg/kubernetes/client/apply.go
pkg/kubernetes/reconcile.go

Instead of just applying namespces before everything else, let's sort
all the objects. There's more inter-dependences between various kinds,
e.g. CRDs need to be applied before the actual custom resources,
StorageClasses before the PVCs, ... .

Sort kubernetes objects before applying.

---

pkg/kubernetes/diff.go

Kubectl 1.18 includes an unfixed issue that causes diff to apply as well – which
is a very bad thing. To avoid this, we now check and abort on that specific
version, prompting the user to downgrade as no fix is yet available.
https://github.com/kubernetes/kubernetes/issues/89762

fix(diff): refuse to diff on kubectl 1.18

---

pkg/tanka/workflow.go

We recently made diff errors in apply non-fatal, but accidentally made
them even more fatal because it can now panic.
Added a check to avoid this

fix(kubernetes): don't panic on failed diff

---

docs/docs/directory-structure.md

In [docs/directory-structure.md#Root-and-Base](https://tanka.dev/directory-structure#root-and-base), `baseDir` and `rootDir` seems to be inverted in the table.

doc: correct docs/directory-structure.md

---

Makefile

Included a GOOS=linux, which makes no sense

fix(make): static on all OS

---

pkg/kubernetes/reconcile.go
pkg/kubernetes/reconcile_test.go

- the original sort code in Reconcile() didn't take into account
the case where two objects of the same kind and name might reside in
different namespace, allowing the sort being non-deterministic at
times.
- testing of the sort code is now implemented.
There might be some refactor pending, since `kubernetes_test.go` also
contains code testing `Reconcile()`, but this is outside the scope of
this PR.

Implement sorting by NS and test object sorting.

---

cmd/tk/main.go
cmd/tk/workflow.go
docs/docs/config.md
docs/docs/garbage-collection.md
docs/doczrc.js
pkg/kubernetes/apply.go
pkg/kubernetes/client/client.go
pkg/kubernetes/client/delete.go
pkg/kubernetes/client/get.go
pkg/kubernetes/client/resources.go
pkg/kubernetes/delete.go
pkg/kubernetes/diff.go
pkg/kubernetes/kubernetes.go
pkg/kubernetes/kubernetes_test.go
pkg/kubernetes/manifest/manifest.go
pkg/kubernetes/reconcile.go
pkg/spec/v1alpha1/config.go
pkg/tanka/parse.go
pkg/tanka/prune.go
pkg/tanka/status.go
pkg/tanka/workflow.go

Implements a mechanism that allows to remove previously created resources that are no longer present in the Jsonnet code, based on internal discussion and tips from @anguslees (thanks!)
Process:
1. Automatically labels all resources with `tanka.dev/environment: <env-name>`
2. Use `tk prune` to remove old ones
3. Fetches all `metadata.uid` of currently present objects
4. Fetches all objects that hold our label
5. Shows diff and prompts for confirm
6. Removes all objects having an unknown UID
Design doc: https://docs.google.com/document/d/1R3_dvXRb2d46GJTb3PQT3hfx2q5sy-ixifSGaWwDM8M
Fixes #88 
/cc @malcolmholmes @captncraig @mplzik

feat: Prune old resources

---

pkg/kubernetes/reconcile_test.go

Required for #902 to pass, no idea why that only happened after merge

fix(test): use full config instead of spec

---

docs/docs/libraries/overriding.md

- use parentheses to evaluate the import path, without which Jsonnet thinks the import is computed
- fix the relative path to the vendored library

Fix vendor patching example

---

docs/docs/installation.md

We now have AUR and `brew`, which is much better for users than
downloading binaries from the internet

doc: recommend package managers

---

pkg/jsonnet/importer.go
pkg/jsonnet/tk.libsonnet.go

`jsonnet.Importer` requires us to return the same `jsonnet.Contents`
each time the same path is imported.
Before, we returned a different `jsonnet.Contents` instance instead,
which the VM noticed and panics.

fix(jsonnet): import "tk" panic

---

cmd/tk/export.go
docs/docs/exporting.md

Minor improvements for `export` to avoid some post-factum scripting when integrating into our stack.

Slightly more flexible `export`

---

cmd/tk/env.go

* introduce a new flag called --names which could output names only
I fixes #296 to make a new flags

feat: Plain names for tk env list (#296)

---

pkg/jsonnet/imports.go

Recursive imports (import cycle) is allowed and handled well in Jsonnet,
but not by our `tool imports`. This adds that property

fix(tools): imports not handling recursion

---

pkg/jsonnet/imports.go

Havin a "canonical" representation of the imports makes the life much
easier when trying to match environment's dependencies against a list of
changed jsonnet/libsonnet files.

Always use non-symlinked paths when listing imports.

---

pkg/jsonnet/imports.go

The change in https://github.com/grafana/tanka/pull/302 only removed
symlinks from the directory path for `main.jsonnet`; this commit also
modifies the code that iteratoes through all the transitive dependencies
to de-symlink them.

Remove symlinks also from dependencies.

---

pkg/process/extract.go

Improves user experience of errors where walking the JSON reaches a primitive that is not a Kubernetes object.

Order keys in walkObj

---

cmd/tk/init.go
pkg/spec/spec.go

Defaults the apiServer URL scheme to `https://` if unset.
Also fixes the message printed by `tk init` to include the scheme
Fixes #287

fix(spec): Default apiServer URL to https

---

Makefile

Adds `windows/amd64` platform, so we also provide `.exe` files for users
interested in Tanka on native Windows.
Everybody please keep in mind this is community support only, Grafana
Labs will not actively develop on Windows and not actively make Tanka
compatible with that platform.
Yet we try not to break it and accept community patches for arising issues.
Fixes #282

chore(packaging): windows/amd64 binary

---

go.mod
go.sum
pkg/kubernetes/client/kubectl.go
pkg/kubernetes/manifest/errors.go
pkg/kubernetes/manifest/manifest.go
pkg/process/extract.go
pkg/process/process.go
pkg/process/process_test.go
pkg/process/testdata/k8s.libsonnet
pkg/process/testdata/tdList.jsonnet

This PR adds native support to Tanka for unwrapping List objects, those
being k8s pseudo objects used to bundle multiple resources into one
object.
To detect whether something is a List or not, the existence of `items`
is used, the same criteria the offical `k8s.io` packages use:
```go
// https://github.com/kubernetes/apimachinery/blob/61490fe38e784592212b24b9878306b09be45ab0/pkg/apis/meta/v1/unstructured/unstructured.go#L54-L61
func (obj *Unstructured) IsList() bool {
field, ok := obj.Object["items"]
if !ok {
return false
}
_, ok = field.([]interface{})
return ok
}
```
Also refactors SchemaError which is now used in `Unwrap` as well. The error now also displays a code snippet, so debugging becomes easier
Fixes #277

feat(process): Unwrap List types

---

cmd/tk/main.go
cmd/tk/workflow.go
pkg/kubernetes/delete.go
pkg/tanka/prune.go
pkg/tanka/tanka.go
pkg/tanka/workflow.go

This can be used to tear down a tanka environment. When doing `tk
delete`, tanka will generate all manifests for an environment and remove
them from kubernetes cluster.
This is a safer variant of the one-liner mentioned at https://github.com/grafana/tanka/issues/155

Implement `tk delete` functionality.

---

cmd/tk/export.go

This change allows to create subfolders via the `--format` flag. 
In order to allow controlledcreation of subfolders and not accidentally do it when there is a `/` in the format the new flag `--allow-subfolder-creation` needs to be set to enable this feature.
Without setting the flag the behavior of the command is equal to before.
Edit: Thanks to @captncraig this uses a template function for format now instead of the less secure way with the flag

Allow export command to create subfolders via file format

---

cmd/tk/export.go

Adds a `--force` flag to `tk export` to skip the check that makes sure
the output dir is empty.
This can be used to merge resources of multiple environments into a
single tree

feat(cli): skip export dir-empty check

---

cmd/tk/export.go

The check was inverted here. Tried to make some of the code a little more obvious.

Fix file exists check

---

docs/docs/namespaces.md
pkg/process/namespace.go

This is a quick and dirty way to NOT add namespaces to  non-namespaced resource types like ClusterRoles or StorageClasses.
I ran into this when trying to export resources to a folder per namespace, and seeing things like ClusterRoles show up in nested namespaces, which is incorrect. It masked issues like multiple environments defining the same object because of the way it did this.
I implemented it as a simple list in namespace.go. If new types are added to the api we can add them here. It requires a little maintenance potentially, but it isn't world ending if we take too long to add something.

Don't attach namespaces to non-namespaced resources

---

docs/docs/targets.md
pkg/process/filter.go
pkg/process/process_test.go

Output filtering (`-t`) now supports excluding objects, by prepending an
exlamation mark (`!`) before the regular expression
Fixes #324

feat(cli): support negative filters

---

cmd/tk/export.go
cmd/tk/jsonnet.go
cmd/tk/workflow.go
docs/docs/jsonnet/injecting-values.md
pkg/jsonnet/eval.go
pkg/tanka/tanka.go

Exposes the TLA functionality of Jsonnet.
BREAKING: Changes the extVar flags to match those of the `jsonnet` CLI
/cc @sbarzowski, would be super cool if you could give the docs added by this PR a quick look if they are complete and correct

feat(jsonnet): top level arguments

---

pkg/kubernetes/manifest/manifest.go
pkg/kubernetes/subsetdiff.go

The manifest.Manifest is a `map[string]interface{}`, which sticks to what `json.Unmarshal` returns, meaning it only includes concrete values, `[]interface{}` and `map[string]interface{}`.
In a v0.10 change I accidentally broke that, without realizing it: https://github.com/grafana/tanka/blob/a6d5fde5aac69dc4d66bb57d5a501e52ba60fada/pkg/kubernetes/manifest/manifest.go#L248
Up to #312, this didn't create any issues. Now however, because we called `Annotations` on all objects, types weren't like they should have been.
This caused subsetdiff to miss annotations, not computing the subset on them at all.
Fixes #318

fix(k8s): consistent types in manifest.Manifest

---

README.md

Makes it point to Grafana Drone instead of Drone Cloud which is no longer used by us

fix(readme): build status indicator

---

pkg/jsonnet/jpath/jpath.go

Problem: Indefinite loop in function findRoot
Root cause: Root path only consider linux "/"
Solution: Detect os at runtime and decide root path. Windows "C:\\", others "/"
Fixes #329

Fix issue #329: Windows indefinite loop

---

cmd/tk/init.go

A new environmental variable was added called `TANKA_JB_PATH` however it's not actually being used to install the packages due to `"jb"` still being hardcoded.

Using jbBinary variable instead of hardcoded jb

---

cmd/tk/args.go

When environment completion is not available the projectRoot is not
reliably detected, tk now suggests any directory instead of an empty
set.
Fixes #352 
@ghostsquad

feat(cli): fallback to PredictDirs

---

go.mod
go.sum
pkg/kubernetes/manifest/manifest.go
pkg/kubernetes/manifest/manifest_test.go

The `manifest` package operates using the assumption that only the JSON
types are present in the `map[string]interface{}`:
- float64 for numbers
- string for texts
- bool for booleans
- nil for null values
The `gopkg.in/yaml` package however also uses `int`, etc. This breaks
our package.
To work around this, the custom `yaml.Marshaller` has been modified to
not actually unmarshal, but call `json.Unmarshal` instead, making both
formats behave exactly the same.
Extensive tests have been added to ensure this.

fix(manifest): yaml unmarshalling

---

pkg/helmraiser/helm.go
pkg/helmraiser/helm_test.go
pkg/jsonnet/native/funcs.go

Abstracts the code that calls `helm template` into a struct method, so
it can be used beyond the Jsonnet interface.
This enables better testing, is more readable and also leverages more of
the existing code in this project.
This is extracted from #355

refactor(helmraiser): Abstract template code

---

pkg/helm/helm.go

Now automatically untars the downloaded Chart artifact, so git can
handle it better.
Is there a use-case for not doing this? Should it be configurable?

feat(tool/charts): untar

---

pkg/kubernetes/diff.go

I've changed the message to encourage users to upgrade to a kubectl version with the fix merged. I felt like encouraging either a downgrade or upgrade may be confusing to users who I assume are running 1.18.X to match up with their cluster versions.  
Closes #328 
Signed-off-by: Jack Baldry <jack.baldry@grafana.com>

Revise diff error message to encourage upgrading kubectl beyond 1.18.0

---

pkg/helm/template.go

As proposed by [this design doc](https://docs.google.com/document/d/171F0cm_VliMStmHe6oy5pAbuXihr-7Cb5yD-vmwqpP8/edit#heading=h.jw0tqbslwqja), this modifies the `helmTemplate` native function in a way that it expects a relative path instead of the `repo/name` identifier for Charts.
Before, this feature relied on the system wide Helm cache, which is independent from the Tanka project and not controlled by git. This does not play well with our aim for hermeticity and strong reproducibility at all.
To overcome this, `helmTemplate` resolves the chart **relative to the calling file**. This suggests to keep Helm Charts as close to the consuming source code as possible.
Using the calling file as a fixpoint is also the only way I came up with that is independent from the current working directory …

feat(helm): Require Charts to be locally available

---

pkg/helm/template.go

Apparently, helm does sometimes return elements in the YAML stream that
consist only of comments – meaning they are empty.
Because they don't pass our validation code, and also because they are
useless we need to ignore them.
Also fixes the name layout, putting `metadata.name` first and `kind`
last, as it was in the original helmraiser PR

fix(helm): ignore empty objects

---

go.mod
go.sum
pkg/jsonnet/eval.go
pkg/jsonnet/jpath/jpath_test.go
pkg/process/data_test.go
pkg/tanka/parse.go
pkg/tanka/parse_test.go
pkg/tanka/tanka.go
pkg/tanka/workflow.go

4a2d018b4cbab1a78b8c3fc20f4c5f7ffe0bad36: Switches from `vm.EvaluateSnippet` to the new `vm.EvaluateFile` and `vm.EvaluateAnonymousSnippet` function classes, which were introduced in https://github.com/google/go-jsonnet/pull/447.
Our `pkg/jsonnet` now has three primary methods:
- `MakeVM(opts)`, which creates a Tanka specific VM, including import paths, native funcs, TLA, extVars, etc
- `EvaluateFile(file, opts)`, which uses above VM to render a file found by the importer
- `Evaluate(filename, snippet, opts)`, which uses above VM to render a piece of code that is not actually on the local file system, but injected from somewhere else
The latter two functions do not much on their own, but stay closer to the current api, where a consumer does not need to know about the VM at all …

refactor: Jsonnet parsing

---

go.sum
pkg/process/process.go
pkg/process/resourceDefaults_test.go
pkg/spec/v1alpha1/config.go

Implements #365 
This allows you to have in your spec.json:
```
"spec": {
"resourceDefaults": {
"labels": {"foo":"bar"},
"annotations": {"whatever/foo": "anything_at_all"},
}
}
```
and those will be applied to EVERY resource in the environment.
It will not overwrite any labels or annotations explicitly defined in your manifests.

Add default labels and annotations from spec.json

---

cmd/tk/jsonnet.go
cmd/tk/util.go
cmd/tk/workflow.go

This allows users to avoid a pager by emptying out the `PAGER` environment variable (setting `PAGER=""`), only defaulting to `less` with posix flags (not supported by busybox `less`) if `PAGER` is unset.
Closes #293

Improve user control of paging

---

cmd/tk/export.go
cmd/tk/jsonnet.go
cmd/tk/status.go
cmd/tk/workflow.go
pkg/kubernetes/delete.go
pkg/tanka/parse.go
pkg/tanka/parse_test.go
pkg/tanka/prune.go
pkg/tanka/status.go
pkg/tanka/tanka.go
pkg/tanka/workflow.go

Refactors our API away from the Modifier pattern to plain old struct arguments.
- This requires less boilerplate. No longer a Setter must be created for each possible field
- Logical separation: Using struct embedding, fields can be properly grouped and scoped for their respective action, etc. This also requires less copying around in memory
- Stricter checking: Every action got its own composed struct type, so only those fields can be set that actually make sense.
Not quite sure who to assign for review on this. This is intended as a refactor in the strict sense, being a no-op

refactor(api): use structs

---

cmd/tk/jsonnet.go
pkg/jsonnet/eval.go
pkg/tanka/parse.go

depends upon #376 
Adds support for `--eval` - can extract a single value from the Jsonnet tree, which can be hidden, can be a string, json, etc.

Add eval to eval

---

go.mod
go.sum

The yaml library update brought along with it [this change](https://github.com/go-yaml/yaml/pull/571) which caused a large number of whitespace only changes in our config. 
I wouldn't normally have a problem with this, but the 0.12 release is already a bit tricky, and I'd rather not complicate it with this.

chore(release): pin goyaml to 2.2.8

---

Makefile
cmd/tk/main.go
pkg/spec/v1alpha1/config.go
pkg/tanka/parse.go

Adds `spec.versions.tanka` to validate the current Tanka version against
a SemVer constraint (e.g. `>=0.12`).
This is a struct and not a top level field to allow for extending in the
future, as there are other versions we could validate as well (Helm,
Kubectl, etc)
I realize we put Tanka into feature freeze for the 0.12 release, but I feel like not having this could make the upgrading to the new version harder

feat: Tanka version constraint

---

cmd/tk/init.go
docs/docs/directory-structure.md
docs/docs/known-issues.md
docs/docs/tutorial/k-lib.mdx
examples/prom-grafana/lib/k.libsonnet

Hi,
`jb` update how dependencies are vendor: https://github.com/jsonnet-bundler/jsonnet-bundler/issues/6.
Current vendor structure is:
```
vendor
├── github.com
│   ├── grafana
│   │   └── jsonnet-libs
│   │       └── ksonnet-util
│   │           └── kausal.libsonnet
│   └── ksonnet
│       └── ksonnet-lib
│           └── ksonnet.beta.4
│               ├── k8s.libsonnet
│               └── k.libsonnet
├── ksonnet.beta.4 -> github.com/ksonnet/ksonnet-lib/ksonnet.beta.4
└── ksonnet-util -> github.com/grafana/jsonnet-libs/ksonnet-util
```
As `jb` provide command to fix import `jb rewrite`, I suppose that symlink will not be supported in future. So I think it is cleaner if generated files from `tk init` are import files from vendor with full path instead symlinks.
Furthermore, I update docs …

Fix dependencies path from generate files

---

CHANGELOG.md

0.12 runs well for over a month internally, so we can release just in time for the community call tomorrow.

chore(release): Changelog for 0.12 stable

---

docs/docs/completion.md
docs/docs/config.md
docs/docs/diff-strategy.md
docs/docs/directory-structure.md
docs/docs/env-vars.md
docs/docs/exporting.md
docs/docs/garbage-collection.md
docs/docs/helm.mdx
docs/docs/installation.mdx
docs/docs/namespaces.md
docs/docs/targets.md
docs/doczrc.js
pkg/helm/jsonnet.go

Adds docs for the upcoming Helm support:
- Reorganizes the "loose" docs pages into categories
- Adds Helm support to "Advanced features"
Also needs https://github.com/grafana/jsonnet-libs/pull/332
I've tagged a lot of people here. If you got time, please read those and think of a less involved user. Is it clear how to use this feature?

doc: helm.template()

---

cmd/tk/status.go

Currently when running `tk status` the output contains the following:
```
InjectLabels: %!s(bool=false)
```
This is caused by using the `%s` format verb which only works on string
By specifying `%v`, go will use the default format for the corresponding datatype

switch format verb for status output

---

cmd/tk/env.go
pkg/jsonnet/jpath/jpath.go

Environment name is the relative path of an env dir. tk env add is incorrectly
using the base dir name. This PR fixes it.
jpath pkg is used to benefit from the existing implementation. FindRoot function
is made public instead of using Resolve because Resolve does many other things
as well, some of which require files that don't exist at that time.
Signed-off-by: Michal Wasilewski <mwasilewski@gmx.com>

fix(cli): Environment name at env creation (#397)

---

docs/docs/installation.mdx
docs/src/components/install/index.js
docs/src/components/install/jb/osx.mdx

I am not 100% sure this is all that is needed, but I noticed today while reading your docs that you didn't indicate jb could be installed through brew right along with tanka so I thought I'd take a stab at fixing that. Hope this helps.

Jsonnet Bundler via brew

---

cmd/tk/tool.go
pkg/jsonnet/eval.go
pkg/jsonnet/imports.go
pkg/jsonnet/jpath/jpath.go
pkg/tanka/parse.go

The change allows the user to run tanka with alternative entrypoints, not limiting to `main.jsonnet` anymore.
This opens the door to using `tk eval` for purposes outside of the Tanka/K8s Environments paradigm. For example, one can
write a library with a `test.jsonnet` and run `tk eval test.jsonnet` in that library. Caveat: it needs to have a
`tkrc.yaml` or `jsonnetfile.json` so Tanka can resolve the JPATH. It also works for `tk export` and `tk show`, beware
that it will add `default` namespace to kubernetes objects, even though a `spec.json` might not exist.
This change is backwards compatible and still defaults to main.jsonnet if no file is given, `tk diff` will still want a
spec.json to connect to a cluster.
Feel free to give feedback/pushback on the idea here too.
I've done a grep on …

feat: allow other entrypoints

---

pkg/helm/charts.go

Fixes https://github.com/grafana/tanka/issues/401

fix(helm): Check prior vendoring of helm charts

---

docs/docs/helm.mdx

Fixes the duplicated `https://`. The diff might look weird, because is a diff on a diff block, but is only one line being modified.

docs(helm): Fix Grafana Helm Charts URL

---

pkg/term/alert.go
pkg/term/alert_test.go

This fixes confirmation prompts on windows by scanning for a line of input and comparing that to the desired prompt. `term.Confirm(...)` is refactored slightly to make it easier to test.
Fixes #347
Note that other tests (not those added in this PR) will fail on windows until #411 is merged.
I've also verified this works on windows:
<details>
<summary> With `tk` `v0.12.0` </summary>
```txt
C:\Users\Nathan\projects\grafana-agent-operator\example [master ≡ +0 ~4 -0 !]> tk apply .\environments\default\
diff -u -N C:\Users\Nathan\AppData\Local\Temp\LIVE-097035773/apiextensions.k8s.io.v1.CustomResourceDefinition..servicemonitors.monitoring.coreos.com C:\Users\Nathan\AppData\Local\Temp\MERGED-483356984/apiextensions.k8s.io.v1.CustomResourceDefinition..servicemonitors.monitoring.coreos.com
--- …
```

term: Fix confirmation prompts on windows

---

cmd/tk/main.go
pkg/tanka/errors.go
pkg/tanka/evaluators.go
pkg/tanka/parse.go
pkg/tanka/parse_test.go
pkg/tanka/tanka.go
pkg/tanka/workflow.go

With inline environments, I introduced quite a bit of complexity to the code base. This is a first attempt at trying to
reduce the complexity.
I've observed this pattern in https://github.com/grafana/cortex-tools/blob/master/pkg/rules/parser.go#L27-L37

refactor(api): Evaluators

---

docs/docs/helm.mdx
pkg/helm/charts.go

Using our Helm integration now gives this:
```
WARNING: "kubernetes-charts.storage.googleapis.com" is deprecated for "stable" and will be deleted Nov. 13, 2020.
WARNING: You should switch to "https://charts.helm.sh/stable" via:
WARNING: helm repo add "stable" "https://charts.helm.sh/stable" --force-update
```
This PR does what they say, and prevents the warnings.

New URL for stable helm repo

---

Dockerfile

:wave: awesome tool! I'm using tanka to do some side projects and I'm setting up some CI/CD pipelines. In the process, I added a helm chart to install redis instances in my k8s cluster and noticed that the tanka docker image doesn't have helm installed. This adds helm to the final built image.
I'm not sure if this is in the scope of this image to be fully honest, or if we want to pin to a specific version of helm inside the image. I'd love some discussion on both of these points if there's any concerns.

Adding helm step to docker image building

---

pkg/helm/charts.go

When calling `tk tool charts vendor`, and a directory already exists at
the expected chart path, recursively delete that directory unless its
Chart.yaml matches the version of the chart specified in chartfile.yaml.
This allows vendored charts whose versions have changed to be downloaded
by tanka users without first removing the charts directory.
Return errors when Chart.yaml doesn't exist, or is malformed.
---
Implements https://github.com/grafana/tanka/issues/419

Vendor helm chart versions based on chartfile.yaml

---

Dockerfile

While the Helm install script handles armv7 well, our CI actually uses a
armv8 CPU running in armv7 mode when building the image, thus reporting
armv8l as the cpu model, which is not handles by the Helm script.
A simpler way of getting the correct binary is to use the Alpine Linux
package from the edge/testing repository, which appears to be very up to
date: https://pkgs.alpinelinux.org/package/edge/testing/aarch64/helm
Fixes #438

chore(docker): fix Helm install on armv7

---

cmd/tk/tool.go

This allows us to export the JSONNET_PATH for use with other tools like
`jsonnet-lint` or `jsonnet-deps`.
Example:
```
eval $(tk tool jpath environment/prod/main.jsonnet)
jsonnet-lint environment/prod/main.jsonnet
```

feat(cmd): use jpath tool to export JSONNET_PATH 

---

pkg/spec/depreciations_test.go
pkg/spec/spec.go
pkg/spec/v1alpha1/environment.go
pkg/tanka/parse.go
pkg/tanka/parse_test.go

This PR sets `metadata.Namespace` at runtime, the path relative to the root. This removes the assumption that name equals
path and also shows up in tk env list --json, which can in turn be used by other tools that want to perform bulk actions
on Tanka environments.
Pulled out of #433 as I think this is useful in the context of inline environments while the pruneMark is way more
controversial.

feat: add metadata.Namespace

---

Dockerfile

Reverts the previous commits attempt to fix Helm on arm32 by using the Alpine package, because as it turns out, there is no alpine package for armhf.
Instead, we now use the offical Helm binaries, and `go env GOOS` and `go env GOARCH` to pick the correct one.
This should work consistently across all platforms.

chore(docker): properly handle arm(32) and arm64

---

cmd/tk/toolCharts.go
docs/docs/helm.mdx
pkg/helm/charts.go
pkg/helm/spec.go

Adds tk tool charts add-repo for adding a repository using the CLI
Fixes #417

feat(tool/charts): add repo cmd

---

cmd/tk/jsonnet.go
cmd/tk/main.go
pkg/jsonnet/eval.go
pkg/tanka/evaluators.go
pkg/tanka/parse.go
pkg/tanka/parse_test.go
pkg/tanka/tanka.go
pkg/tanka/workflow.go

Another iteration on evaluators. I hope this reduces code complexity by some degree, instead of passing functions along
through `ParseOpts`, this now passes an `EvalScript` along. It should make the API more flexible as arbitrary jsonnet
can be injected before evaluation.
Note: This (re)moves the `EvalPattern` option as it can now be called by the CLI function that uses it.
Review tip: hide whitespace changes.

refactor(api): use EvalScript on JsonnetOpts

---

cmd/tk/jsonnet.go
pkg/tanka/parse.go

ref: #457
Figured that EvalScript might as well be used in combination with Environments. Removing this early returns should allow that.
Also, it should only be set if evalPattern is set in the `tk eval`.

fix: EvalScript issues

---

pkg/tanka/export.go

The export wrote the absolute path to the manifest.json, that is not portable. Writing the relative path intead.

fix(api): write relative path to manifest.json

---

cmd/tk/jsonnet.go
pkg/tanka/evaluators.go

Kudos @malcolmholmes for proposing this solution.
fixes #462

fix(cli): ensure TLACode works with EvalScript

---

cmd/tk/main.go
cmd/tk/prefix.go

In analogy to the git- prefixed commands, this finds all executable on
PATH that look like `tk-<command>` and run them as `tk <command>`.
Implementation example:
```
$ cat /usr/bin/tk-jq
#!/usr/bin/env sh
${EXECUTABLE} eval ${@:2} | jq $1
$ echo "{ tanka: 'cool' }" > main.jsonnet
$ tk jq .tanka main.jsonnet
"cool"
```
This concept intends to foster extensions that work well with Tanka, for example encrypt/decrypt secrets during runtime, alternative diff tools, integration with third party API clients, ...

feat(cli): run commands with tk- prefix on PATH

---

docs/docs/helm.mdx

I had some trouble figuring out how to use the Charttool to install charts from an existing `chartfile.yaml`, so I thought it would be nice to add a section explicitly showing the `tk tool charts vendor` call.

docs(helm): add installing from chartfile section

---

cmd/tk/env.go
cmd/tk/export.go
pkg/tanka/inline.go
pkg/tanka/load.go
pkg/tanka/static.go

Introduces a new functionality called Peek with behaves like Load, but
only loads metadata.
Because this is much faster than full loading, this can be used at
places where only metadata is required.
This formalizes behavior that was previously possible by passing
`EnvsOnlyEvalScript`. The benefit of having this as an interface
implementation is that it can make better use of underlying details,
such as that the static loader does need to start a costly Jsonnet VM
for only parsing `spec.json`

feat(api): Peek 

---

pkg/tanka/environments.go
pkg/tanka/export.go
pkg/tanka/load.go

Restore functionality that allowed for parallel processing for export. This functionality was mistakenly removed in
#459, I should have not approved that. I intended to bring that functionality back in combination with processing
multiple inline environments, but the recent discussions and PRs with refactorings give me an indication we better
restore it ASAP and have more discussions around the multiple inline environments feature.
Here is what it is actually restoring:
- LoadManifests: https://github.com/grafana/tanka/pull/459/files#diff-e5a9edc90a041a304d2a9ce3c9cd065defeda6af8b2c264fdd004e0cbd7af311L88-L103
- export.go: https://github.com/grafana/tanka/pull/459/files#diff-cde4b57e55103add29a57ad016a8173f3293f9d5442fe4d018e9a5e1933a8e1a
- environments.go: …

fix(api): restore parallel export

---

cmd/tk/args.go
cmd/tk/env.go
cmd/tk/export.go
pkg/tanka/environments.go
pkg/tanka/list.go

Introduces `tanka.ListEnvs` for discovering all nested environments starting from any given directory on the filesystem.
This is now implemented by concurrently testing each subfolder of the given directory as to whether it is a valid environment. The recursion stops if any directory is a valid environment.
Switches all occurences of `FindBaseDirs` to the more performant `ListEnvs` algorithm.
A quick `tk env list` on our config repo gave the following:
```
Before: tk env list  25.40s user 0.69s system 946% cpu 2.757 total
After:  tk env list  1.61s  user 0.37s system 811% cpu 0.243 total
```
Needs rebasing on #467 once merged

feat(api): Environment discovery 

---

pkg/spec/spec.go
pkg/tanka/inline.go
pkg/tanka/load_test.go
pkg/tanka/static.go

This is an edge case, `namespace` should match the full execution path if `path` is a file that is not `main.jsonnet`.

fix: correct namespace when using a file

---

cmd/tk/export.go
pkg/tanka/export.go
pkg/tanka/parallel.go
pkg/tanka/tanka.go

As suggested in #471, this refactors the parallel functions to use the chan idioms. It also makes `parallelOpts` a
private struct.

refactor: parallel

---

cmd/tk/export.go
pkg/tanka/parallel.go

This partially reverts changes made in #473.
Turns out the workers kept waiting for `outCh` to be read, this only happens after all 'jobs' have been launched. But as
the limited number of workers kept waiting, no new jobs could be launched.
One of the concerns in #6611 was that a pointer was passed back, this is not the case anymore. The env is now copied
instead of passing along a pointer.

fix: recursive export

---

cmd/tk/args.go
cmd/tk/env.go
cmd/tk/export.go
cmd/tk/flags.go
cmd/tk/workflow.go
pkg/tanka/errors.go
pkg/tanka/evaluators.go
pkg/tanka/export.go
pkg/tanka/find.go
pkg/tanka/inline.go
pkg/tanka/list.go
pkg/tanka/load.go
pkg/tanka/parallel.go
pkg/tanka/static.go
pkg/tanka/tanka.go

This PR provides a solution to work with multiple inline environments. Bulk operations like `tk export --recursive` and
`tk env list` will now be able to work on multiple inline environments found in a `main.jsonnet`. The regular workflow
commands like `tk apply`, `tk show`, etc. will require the `--name` flag if multiple environments are present.
Ideally I'd like an interactive UI for selecting an environment, however there are multiple ways to do it with shell
integrations, for example `fzf` has been brought up in recent discussions. If we do want an integrated UI, I propose to
introduce that in a separate PR.
closes #432
be9dafc is a rebase of 91651e9 (kudos @sh0rez), which could also have its own PR, this PR just takes it one step further.
~commit c15952a comes from #475, need a …

feat: multiple inline environments

---

cmd/tk/workflow.go
pkg/kubernetes/apply.go
pkg/kubernetes/client/client.go
pkg/kubernetes/client/errors.go
pkg/kubernetes/client/get.go
pkg/kubernetes/diff.go
pkg/kubernetes/kubernetes.go
pkg/tanka/workflow.go

Fixes https://github.com/grafana/tanka/issues/416 in line with what @malcolmholmes suggested.
Adds `--with-prune` option to `diff` command. This makes it possible to see a full diff of both added and deleted resources.
I'm not sure if it's okay to add `--ignore-not-found` to `GetByState()` or if it should be passed as argument to it. I have left a `TODO` in the code.
Let me know if I should change anything.

feat(cli): Add --with-prune option for diff command

---

pkg/jsonnet/eval.go
pkg/tanka/inline.go
pkg/tanka/load.go
pkg/tanka/parallel.go
pkg/tanka/static.go

In a recent refactor (https://github.com/grafana/tanka/pull/459) we lost `tk.env` respectivley
`std.extVar("tanka.dev/environment")` support.
For static environment this however is still the way to go for accessing
env data from within Jsonnet.
This PR restores the functionality and also makes Tanka properly fail
with a message when attempting to use `tk.env` from an inline environment
Fixes #480

fix(jsonnet): Restore tk.env

---

cmd/tk/flags.go

Changes the help message of --target / -t so that it reflects the
accurate format and the fact it uses regex.
Fixes #452 
/cc @ghostsquad

doc: improve --target help

---

pkg/tanka/evaluators.go
pkg/tanka/inline.go
pkg/tanka/load.go
pkg/tanka/static.go
pkg/tanka/workflow.go

To run `tk eval`, we also need to handle `import "tk"` and related. As this behavior is specific to the Loader, it seems to make sense to use the Loader interface for this.
Fixes #480 again. :)

fix(jsonnet): EvalJsonnet through Loader interface

---

docs/docs/libraries/overriding.md

Fixes #461 
* Jsonnet importer rules impacts file overrides, let's ensure that our
docs are a bit more clear
* This adds an example inside of our documentation for assisting others
whom may run into problematic behavior

Improves documentation regarding import path

---

Dockerfile

Since the Alpine images went to 3.13 we are experiencing [this issue](https://gitlab.alpinelinux.org/alpine/aports/-/issues/12343) on arm 32-bit. We followed the advise on from the release notes but that didn't resolve the issues.
Downgrading this image now for the release. We can resolve this later on.

fix(docker): downgrade alpine images

---

cmd/tk/env.go
cmd/tk/flags.go

Implements: https://github.com/grafana/tanka/issues/504
Plus fixes minor errors in `tk env set` output.

Add --inject-labels to `tk env add/set`

---

cmd/tk/workflow.go
pkg/tanka/workflow.go

That causes `tk diff` to exit with 0 when there is a diff present.

Add `tk diff --exit-zero` flag

---

cmd/tk/workflow.go
pkg/spec/v1alpha1/environment.go
pkg/tanka/load_test.go
pkg/tanka/testdata/cases/withduplicateenv/main.jsonnet

By adding the name field to the prune flags. This just works due to
environment loading logic being shared across subcommands.
Base NameLabel on both namespace and name. The namespace of inline
environments includes the path on disk, and multiple environments with
the same given name cannot be loaded from the same path on disk, so the
tuple of these 2 fields is guaranteed to be unique.
Use a truncated hash of a combination of these 2 fields to form a label
that is guaranteed to fit in Kubernetes' 63 character limit for label
values.
This fixes a bug in which 2 inline environments with identical
metadata.Name, applied separately from 2 paths on disk to the same
Kubernetes namespace would create resources with identical
`tanka.dev/environment` labels, and so pruning one release would delete …

Allow inline environments to be pruned

---

cmd/tk/env.go

I'd like to use the output of `tk env list --json` in various places and check if something has changed in the
environments metadata by comparing the output with standard diff tools. Due to the async nature of FindEnvs, the output
is random. This adds a sorting algorithm on that output so they are alphabetically sorted by name so we get consistent
output.

feat(cli): sort environments by name

---

cmd/tk/tool.go
pkg/jsonnet/imports.go

`tk tool imports` is a really useful tool for identify imports within a Jsonnet codebase.
However, if you use it with a complex codebase, it can report "couldn't load foo/bar.libsonnet" without telling you where it was when it failed. This very minor tweak gives direct feedback as to where the error is facilitating an easy and immediate fix.

fix(tool/imports): add path info to error message

---

cmd/tk/tool.go

With inline environments, this should be an option.

fix(tools): allow files on imports tool

---

pkg/tanka/prune.go

closes #311
This is a small change that could save someone a lot of trouble. 
We tried to do a few smarter things considering namespaces but they are quite complex from our current perspective (see #477). I would not be opposed to increasing the safeguards on this in the future

feat(prune): warn before deleting namespaces

---

pkg/kubernetes/client/delete.go
pkg/tanka/prune.go
pkg/tanka/workflow.go

On commands that produce diffs: diff, apply, and prune.
It is desirable for some use cases to parse diff output from `kubectl
diff` (e.g. secret redaction until
https://github.com/kubernetes/kubernetes/issues/87840 is resolved). This
is a lot easier when diff and non-diff output are not combined on the
same channel, stdout.
This commit moves diagnostic, non-diff output for the 3 relevant
subcommands to stderr.
See https://gitlab.com/gitlab-com/gl-infra/k8s-workloads/tanka-deployments/-/merge_requests/123 for an example of a diff-parsing workflow that would be made easier by this split 🙂.

fix(cli): Split diff and non-diff output

---

cmd/tk/args.go
pkg/tanka/errors.go
pkg/tanka/find.go

On export of inline environments, Tanka would silently exit if the List failed. This catches the error and returns it.

fix(cli): Do not silently fail on find/List

---

cmd/tk/export.go
pkg/kubernetes/manifest/manifest.go

Adds support for `tk show` and `tk export` to handle K8s objects that use `.metadata.generateName` instead of `.metadata.name`.
Changes the default format (being backwards compatible) to also support outputting such files with `tk export`.

feat: support .metadata.generateName (#526)

---

pkg/helm/charts.go

We currently run `helm repo update` every time we run `tk tool charts
vendor`. Some tanka users may check in their charts directory to avoid
many network calls to helm repositories in CI, which can be flaky. By
delaying the `helm repo update` call until there is a chart to pull, we
can better support these workflows.
Hopefully a non-broken version of https://github.com/grafana/tanka/pull/507!

Only update helm repositories when necessary

---

docs/docs/directory-structure.md

Fix this broken link to the source code that had broken due to a change in
filename in 12f771628078e282a2c39c93e319cdcf1bae103c.

docs: fix broken link to spec.json Golang source

---

pkg/kubernetes/client/client.go
pkg/kubernetes/client/kubectl.go
pkg/kubernetes/diff.go
pkg/kubernetes/manifest/manifest.go

Fixes #301.
If we don't have permission to list namespaces, take a (potentially) slower approach, filter
out the namespaces that are referenced in the resources, and check each of those in turn.
These can then be used to identify whether a diff will break, as before.

Don't fail on listing namespaces

---

pkg/helm/template.go

This will allow users disabling hooks when rendering manifests from helm templates.
A use-case is, for example, installing Loki on EKS from https://github.com/grafana/helm-charts/tree/main/charts/loki-stack
When running `tk diff` you'll get an error
```
Error from server (BadRequest): admission webhook "iam-for-pods.amazonaws.com" does not support dry run
```
This isn't an issue in Tanka but the scope of this functionality is not limited to it and I think you can very much find use-cases outside of this example.
A potential improvement here could be to allow passing any args to `helm template` maybe using an array without any validation.

Add support for `--no-hooks` switch in Helm template

---

docs/docs/faq.md

Adding a missing `)` in the `What about kubecfg ?` section of the FAQ

fix(docs): typo in faq

---

cmd/tk/export.go
pkg/tanka/export.go
pkg/tanka/parallel.go

On the internal Grafana Labs jsonnet code base, this can improve the performance of the export significantly. Tests on my local
machine went from 2m08s to 1m32s.

perf(export): only call FindEnvs once

---

.drone/drone.jsonnet
.drone/drone.yml

Currently, the executables within the docker images have no version
```
➜  ~ docker run --rm -it grafana/tanka:0.15.0 --version
tk version 014fae3
```
By fetching the tags before building the execs, this should be fixed

Fetch tags on docker builds

---

docs/docs/helm.mdx

I almost opened a PR to shim `--include-crds` into the `helm template` invocation, until I dug around and discovered it's already available.
Hoping this documentation will save folks some time.

Document helm template flags

---

cmd/tk/init.go
docs/docs/directory-structure.md
docs/docs/known-issues.md
docs/docs/tutorial/environments.mdx
docs/docs/tutorial/k-lib.mdx
examples/prom-grafana/environments/prom-grafana/dev/main.jsonnet
examples/prom-grafana/environments/prom-grafana/patched/main.jsonnet
examples/prom-grafana/jsonnetfile.json
examples/prom-grafana/jsonnetfile.lock.json
examples/prom-grafana/lib/k.libsonnet
examples/prom-grafana/lib/prom-grafana/prom-grafana.libsonnet

I would like to propose making [k8s-alpha](https://github.com/jsonnet-libs/k8s-alpha) the default library we refer to
instead of the long ago abandoned [ksonnet-lib](https://github.com/ksonnet/ksonnet-lib/).
Grafana Labs has been using `k8s-alpha` since its inception by @sh0rez over a year ago this month. The
[ksonnet-util](https://github.com/grafana/jsonnet-libs/tree/master/ksonnet-util) has since been refactored and provides
an adequate compatibility layer to make the transition seamless.
This PR updates the `tk init` command to initiate a Tanka directory structure using the `k8s-alpha` library and replaces
most if not all `ksonnet-lib` references with `k8s-alpha` in the docs. I also sneaked in a few Jsonnet best practices,
not stacking Jsonnet libraries on the root.

feat: s/ksonnet-lib/k8s-alpha

---

cmd/tk/workflow.go
docs/docs/config.md
docs/docs/diff-strategy.md
pkg/kubernetes/client/diff.go
pkg/kubernetes/kubernetes.go
pkg/tanka/workflow.go

Fixes https://github.com/grafana/tanka/issues/332
In the "validate" mode, diff will be called an additional time with "--server-side"
The reason why it's called an additional time is because this argument will add server-only attributes to the diff such as "last-applied-configuration", users probably don't want to see these since they will change on every run
By adding a second diff call that's only use to find errors, we keep the same diff as before but we add an extra validation
Let me know if you think that this solution is adequate. I left the existing "native" mode as the default
I also didn't add any tests, some guidance would be appreciated here. I might be mistaken but there doesn't seem to be any tests around Kubernetes.client.diff, is this because it meant to stay without any …

Add "validate" diff strategy

---

.vscode/settings.json
pkg/tanka/export.go
pkg/tanka/export_test.go

During `tk export` path separators are temporarily replaced with `BEL` char in order to protect paths from being mixed with template output. But when there is a slash in a template action (e.g. `{{index .metadata.labels "app.kubernetes.io/name"}}`, that slash also got replaced, and the template did not work as expected.
This fix ensures that the BEL replacement only occurs within the text portions of the template, and the action blocks are being preserved.
Fixes #568

fix: make export --format respect "/" in template actions

---

pkg/tanka/evaluators.go
pkg/tanka/evaluators_test.go
pkg/tanka/testdata/cases/withtlas/main.jsonnet

While running the `tk apply` command with multiple `--tla-code` arguments, each containing a `key='value'` parameter, I noticed that the JSONNET code would not receive them correctly. More specifically, instead of being passed as named parameters, they are passed as positional parameters and since they're stored in a [`jsonnet.InjectedCode`](https://github.com/grafana/tanka/blob/17da685bbff3baee75e529b13c19d8f047015395/pkg/jsonnet/eval.go#L16) map, they end up being serialised in an arbitrary order which differs each time Tanka is run. I added a test in this PR which highlights this issue (you might need to run it multiple times to get a failure).
Note that this issue only surfaces when using multiple `--tla-code` args when calling `tk apply`.
I am rather new to this tool, so I'm not …

Fix support for multiple --tla-code arguments

---

pkg/helm/template.go

Helm expects the --api-versions flag to be passed for each API, not once with a comma-separated list of APIs.
Fixes #573.

fix(helm): Pass multiple --api-versions flags to Helm 

---

docs/docs/helm.mdx
pkg/helm/template.go

This PR adds the support to specify a custom Kubernetes version when using `helm` feature. 
It would enable to use  helm charts such as [this](https://github.com/dexidp/helm-charts/blob/master/charts/dex/templates/ingress.yaml#L4)  for older kubernetes version easier. We use  `tk export` in CI (docker). Thus, helm cannot detect server's version and fall back to default built-in. 
As workaround, I downgraded the helm to the version where buit-in KubeVersion matches k8s version of the k8s clusters.
It would be much nicer to define the k8s version natively.

feat: Add support to specify `--kube-version` in Helm template

---

cmd/tk/init.go
docs/docs/directory-structure.md
docs/docs/known-issues.md
docs/docs/tutorial/k-lib.mdx
examples/prom-grafana/jsonnetfile.json
examples/prom-grafana/jsonnetfile.lock.json
examples/prom-grafana/lib/k.libsonnet

ref: https://github.com/jsonnet-libs/k8s/pull/39
This library was renamed upstream.

chore: s/k8s-alpha/k8s-libsonnet

---

cmd/tk/init.go

Preserves compatibility with versions before 0.16.0.
#563 redefined flag as string, to optionally specify the desired k8s version. However only `--k8s=true` and  `--k8s=1.18` work but `--k8s=false` doesn't.

Allow to specify `--k8s=false` for `tk init`

---

pkg/process/process.go

In case we're loading lots of files, having the environment is important context

Add more context when `extract` fails

---

pkg/tanka/evaluators.go

It is possible to reference the data object in the environment spec, however this doesn't
work if we remove it. Hiding should be sufficient to get the speed boost from lazy
loading.
The example references `this.data` outside the `data: {}` block, which is perfectly valid although I would discourage that, I'd rather suggest that `data` receives information from the environment it belongs to than the other way around.
Example:
```
local clusterEnvConfig = { namespace: 'a' };
{
local this = self,
apiVersion: 'tanka.dev/v1alpha1',
kind: 'Environment',
metadata: {
name: 'environments/my-app/local',
},
spec: {
namespace: this.data.app._config.namespace,
},
data: {
app: { _config:: { namespace: 'b' } } +
{
_config+:: clusterEnvConfig,
app+: {
_config+:: {
image: 'localhost:5000/my-app',
},
},
}, …
```

fix: Do not remove data

---

go.mod
go.sum

In particular, this contains a fix to not output an error message when running `tk` with no args, or `tk --help`.
I was seeing:
```
laney@sherwood (main|✚2)> tk --help
Error: tanka <3 jsonnet
[ help output here ]
```
which made me think that jsonnet was missing or something. Actually I think it's a fix which is in `cli 0.2.0`: https://github.com/go-clix/cli/commit/6e2d8d038d677555eaebe90a1db2951aed61ad40. When building with this version, that error message isn't shown any more.

Bump `cli` to 0.2.0

---

cmd/tk/flags.go
cmd/tk/workflow.go
docs/docs/inline-environments.mdx
pkg/tanka/evaluators.go
pkg/tanka/inline.go
pkg/tanka/load_test.go
pkg/tanka/testdata/cases/multiple-inline-envs/main.jsonnet

Say I get this output:
```
$ tk diff tanka/environments/my-project
Error: found multiple Environments in 'tanka/environments/my-project':
- environments/my-project/dev
- environments/my-project/prod
```
I can now rerun this command with `--name dev` or `--name ops` instead of the whole environment name
When more than one environment matches, the same message as before is given

Allow partial matches in the --name option

---

pkg/kubernetes/client/resources.go
pkg/kubernetes/client/resources_test.go
pkg/kubernetes/diff_test.go

For sometime `tk pruning` fails, as my cluster has overlapping CRD names/mismatching Kind and Name fields . Errors persisted like this:
```
$ tk prune environments/default
fetching UID's .. done 555.50452ms
fetching previously created resources .. Error: error: the server doesn't have a resource type "NetworkAttachmentDefinition"
```
The reason why this was happing was a failed parsing of the `-o wide` table of `kubectl api-resources`: The field `APIGROUP` no longer exists and is now part of `APIVERSION`.

Fix api-resources table parsing

---

.drone/drone.yml
.drone/release-note.md

It is not showing properly in all locations. Having it as an absolute URL that points to the `main` branch should make it work everywhere
Regenerated the drone.yml file with the newest Drone CLI version which is why everything changed
Closes https://github.com/grafana/tanka/issues/617

fix: Absolute release notes link

---

cmd/tk/flags.go
pkg/jsonnet/eval.go

This can be useful, as a debugging option or a permanent fix, when you get `max stack frames exceeded`
Currently, the only way to debug jsonnet failing with that error is to use the jsonnet executable. I'd rather use Tanka :)

Add `--max-stack` jsonnet option

---

CHANGELOG.md
Dockerfile

I added some info about how to migrate gradually
Also fix the docker build for the tanka image. It is failing because the latest kustomize release is not actually kustomize, it's kyaml

Add changelog entry for 0.19.0

---

pkg/tanka/parallel.go

This will allow us to parse the log lines and continuously output the slowest environments

Add elapsed time log line on export

---

CHANGELOG.md
cmd/tk/workflow.go
pkg/kubernetes/client/apply.go
pkg/kubernetes/client/apply_test.go
pkg/kubernetes/client/client.go
pkg/kubernetes/client/delete.go
pkg/kubernetes/client/delete_test.go
pkg/tanka/prune.go
pkg/tanka/workflow.go

Fixes #666.
* add --dry-run kubectl option to `apply`,
`delete`, `prune`
* add some simple testing to pkg/kubernetes/client

feature: add --dry-run kubectl option

---

docs/docs/jsonnet/native-functions.md

This reflects the true names of native functions
Fixes #632

Change `YAML` and `JSON` to `Yaml` and `Json` in the docs

---

cmd/tk/export.go

Context: At GrafanaLabs, we are currently trying to optimise how long it takes us to do a `tk export` operation of our jsonnet codebase. 
We are currently testing different alternatives, one of them is leveraging a memory ballast to reduce the amount of time spent doing garbage collection.
I'm currently working on getting some hard data to back that up, but in the meantime, I'm proposing this PR which introduces a memory ballast behind a hidden flag for `tk export`.
[1]: https://blog.twitch.tv/en/2019/04/10/go-memory-ballast-how-i-learnt-to-stop-worrying-and-love-the-heap/

tk/export: introduce a configurable memory ballast

---

cmd/tk/flags.go

Backticks in a flag description have a special meaning, in both standard`flag` and the `pflag` package used here. 
Because of this, flag was described as:
--inject-labels tk prune       add tanka environment label to each created resource. Required for tk prune.
Now it will look like:
--inject-labels                add tanka environment label to each created resource. Required for 'tk prune'.
See https://github.com/spf13/pflag/issues/200
Signed-off-by: Oleg Zaytsev <mail@olegzaytsev.com>

Remove backticks from -inject-labels flag desc

---

pkg/kubernetes/diff.go

With an API server for which I'm not authentified with correctly, `tanka` would panic with `target must be a non-nil pointer` because of a call to `errors.As`. Since we are actually only checking the type of the error and not its content, `errors.Is` can be used here. The It could also be moved to a variable to avoid creating a new instance each time just to check if it's of the right type.
This was happening trying to show the diff because it seems I'm not configured correctly.
```
WARNING: version difference between client (1.23) and server (1.20) exceeds the supported minor version skew of +/-1
Error from server (Forbidden): namespaces "default" is forbidden: User "<email>" cannot get resource "namespaces" in API group "" in the namespace "default": requires one of …
```

Fix `target must be a non-nil pointer`

---

docs/docs/config.md
pkg/kubernetes/client/context.go
pkg/kubernetes/client/kubectl.go
pkg/kubernetes/kubernetes.go
pkg/spec/spec.go
pkg/spec/v1alpha1/environment.go
pkg/tanka/load.go

https://github.com/grafana/tanka/issues/58#issuecomment-1054952428
I appreciate the protection `spec.apiServer` provides, but Tanka does not work for our environments without support for matching on context names. I'm happy to update docs if this is something that would potentially be merged.
Our use case is summed up in the comment at the top.
Example `spec.json`
```go
{
"apiVersion": "tanka.dev/v1alpha1",
"kind": "Environment",
"metadata": {
"name": "environments/development"
},
"spec": {
"contextNames": ["automation-generated-context", "local-generated-context"],
"namespace": "default",
"resourceDefaults": {},
"expectVersions": {}
}
}
```
There's also a bug this PR fixes with an empty env.Spec.APIServer where the value will never be an empty string in `(l LoadResult) Connect()` because …

Adds support for specifying valid context names for an environment

---

.pre-commit-hooks.yaml

This PR adds support for [pre-commit.com](https://pre-commit.com/) and `tk fmt` command specifically. One can use it either with `pre-commit` locally or [pre-commit.ci](https://pre-commit.ci/) by introducing `.pre-commit-config.yaml` at the root repository level, e.g.:
```yaml
repos:
- repo: https://github.com/grafana/tanka
rev: v0.20.1
hooks:
- id: tanka-format
```
See:
- https://pre-commit.com for more information
- https://pre-commit.com/hooks.html for more hooks

feature: add support for pre-commit hooks

---

cmd/tk/lint.go
cmd/tk/main.go
cmd/tk/tool.go
pkg/jsonnet/eval.go
pkg/jsonnet/files.go
pkg/jsonnet/imports.go
pkg/jsonnet/jpath/dirs_test.go
pkg/jsonnet/jpath/jpath.go
pkg/jsonnet/lint.go
pkg/tanka/format.go

Like `fmt`, this takes a list of dirs/files as argument and evaluates them with the go-jsonnet lint utility
The linting results are directly printed out to stderr
If there are any linting errors, the command exit with status code 1
Closes https://github.com/grafana/tanka/issues/342

Add `tk lint` command

---

cmd/tk/workflow.go
pkg/tanka/workflow.go

This pull request adds a diff strategy of `none` for `tk apply` that completely suppresses diffing before the apply operation.
The reason I'm submitting this is that I'm using Tanka to create a very large set of Kubernetes resources and it takes 5 to 10 minutes to perform the diff operation before getting to the apply stage.  Since I often use a `tk diff` myself first, before the `tk apply`, I don't need the diff that's part of `apply` in some cases.  Also, when our automated job runs to do a `tk apply`, it uses the `--dangerous-auto-approve` option, with no human present observe the diff output.  The 5 to 10 minute delay in this step of the automation makes the automation job run longer that desired, delaying the deployment of the things that come _after_ this step.
I would like to …

Support a diff-strategy of "none" for "tk apply" to suppress diffing.

---

pkg/helm/charts.go

When chartfile.yaml requirements are parsed, version string is converted into a
semver.Version struct, dropping "optional" v prefix from the version. Match
this behaviour for Chart.yaml version so that they can be compared with each
other.
Closes #701

Compare semvers when checking if existing chart is up-to-date

---

docs/docs/diff-strategy.md
pkg/kubernetes/client/diff.go
pkg/tanka/workflow.go

Interactive diff utilities such as vimdiff do not work unless kubectl is
started with the current TTY as stdout.
If the environment variable KUBECTL_EXTERNAL_DIFF is set, don't assign
the normal string buffer to stdout, use the parent's stdout instead.
Fixes #671

Support interactive diff utilities

---

pkg/helm/charts.go
pkg/helm/charts_test.go
pkg/helm/spec.go

Closes https://github.com/grafana/tanka/issues/508
Whenever two charts will end up in the same dir, tanka will exit before doing anything
Ex, these two versions would end up in the flagger dir:
```yaml
directory: charts
repositories:
- name: flagger
url: https://flagger.app
requires:
- chart: flagger/flagger
version: 1.16.1
- chart: flagger/flagger
version: 1.17.0
version: 1
```
```console
$ tk tool charts vendor
Error: Output directory conflicts found:
- output directory "flagger" is used twice, by charts "flagger/flagger@1.16.1" and "flagger/flagger@1.17.0"
```
It checks in both `add` and `vendor` commands to handle the case where someone writes their YAML manually

Charts: Check for output dir conflicts

---

cmd/tk/env.go
cmd/tk/flags.go

This compliments https://github.com/grafana/tanka/pull/674 and probably should have been in there to begin with. 
This PR adds support for `contextNames` using `tk env add` and `tk env set` commands. It leverages the `Connect` method to check validity of the resulting config.
Below are a few examples, including cases that would throw errors
```
(~/Code) Nash $ mkdir example-tk && cd example-tk
(~/Code/example-tk) Nash $ tk init
GET https://github.com/jsonnet-libs/k8s-libsonnet/archive/1942ec15993b5a273569bb9a59d522b01522d0db.tar.gz 200
GET https://github.com/grafana/jsonnet-libs/archive/73396f2821466dd8f91181e7ee4513e0a8ea45b3.tar.gz 200
Directory structure set up! Remember to configure the API endpoint:
`tk env set environments/default --server=https://127.0.0.1:6443`
(~/Code/example-tk) …
```

Adds support for contextNames in tk env subcommands

---

pkg/helm/charts.go
pkg/helm/charts_test.go
pkg/helm/spec.go

Closes https://github.com/grafana/tanka/issues/691 which is mostly a failure of error messages imo
Instead of getting a `no such file`, the error is now: 
```console
$ tk tool charts add https://helm.releases.hashicorp.com/vault@0.19.0
Adding 1 Charts ...
Skipping https://helm.releases.hashicorp.com/vault@0.19.0: not of form 'repo/chart@version(:path)' where repo contains no special characters.
Error: 1 Chart(s) were skipped. Please check above logs for details
```
Also, adding an invalid repo now prints out a relevant error message instead of failing in helm commands
```console
$ tk tool charts add-repo https://helm.releases.hashicorp.com  https://helm.releases.hashicorp.com
Skipping https://helm.releases.hashicorp.com: invalid name. cannot contain any special characters.
Error: 1 …
```

Charts: Tighten validations

---

cmd/tk/export.go
docs/docs/exporting.md

We've been using it for a [long while](https://github.com/grafana/tanka/pull/669) now, works very well!
Also documented it

Export: Un-hide the memory ballast setting

---

CHANGELOG.md
pkg/helm/charts.go
pkg/helm/charts_test.go

Charts with a custom directory defined are getting pruned 🤦

Helm Charts: Fix `vendor --prune` for custom dirs

---

CHANGELOG.md
pkg/helm/charts.go
pkg/helm/charts_test.go
pkg/helm/spec.go

This one was pre-existing :)
Given this chartfile:
```yaml
repositories:
- name: prefect
url: https://prefecthq.github.io/server/
requires:
- chart: prefect
version: '2022.04.14'
version: 1
```
We get a panic because the name cannot be split into its two parts
It's not possible to add this dependency using the `add` command but given that we want to also support manual edits to the yaml file, additional validation can be nice

Helm Charts: Prevent vendor panic by adding validation

---

CHANGELOG.md
pkg/helm/helm.go

Closes https://github.com/grafana/tanka/issues/719
By using `/tmp` as a pull target, we possibly pull to a different disk than the destination
This makes `os.Rename` impossible
To fix this, we can pull to a temporary dir within the destination instead

Helm Charts: Fix cross-device link error

---

docs/src/components/install/jb/go.mdx
docs/src/components/install/tk/go.mdx

`go get` & `go install` behavior has changed since Go 1.17: https://go.dev/doc/go-get-install-deprecation

doc: update instructions for installing from source

---

README.md
docs/docs/exporting.md
docs/docs/faq.md
docs/docs/helm.mdx
docs/docs/installation.mdx
docs/docs/jsonnet/native-functions.md
docs/docs/jsonnet/overview.md
docs/docs/kustomize.mdx
docs/docs/targets.md
docs/docs/tutorial/jsonnet.mdx

Closes https://github.com/grafana/tanka/issues/726
I ran a linkchecker (https://github.com/grafana/tanka/pull/737) which found a bunch of issues
It unfortunately has a bunch of unrelated errors so I'm not pushing it through but here are the fixes for broken links in the docs

Docs: Fix broken links and redirects

---

pkg/kubernetes/client/context.go

Currently, if you have two contexts:
- my-cluster-dev
- my-cluster and you try to apply to `my-cluster`, it will match the first one

Use exact match to find context from API server

---

.drone/drone.jsonnet
.drone/drone.yml

Currently, two Drone runs are triggered, one for the push to the branch and one for the PR Example: https://github.com/grafana/tanka/pull/752
With this change, only one CI run will be triggered on PRs

Drone: Only run tests once on PRs

---

pkg/helm/charts.go
pkg/helm/charts_test.go

Closes https://github.com/grafana/tanka/issues/749 
Currently, the case where a chart dir is missing is handled by the `vendor` command, the dir will be re-vendored 
However, if the dir is emptied (an example is git, which tracks files but not dirs, if a chart deletion is pulled from git, the dir will remain), Tanka throws an error

Helm: Handle dirs missing the `Chart.yaml` file

---

cmd/tk/flags.go
cmd/tk/workflow.go
cmd/tk/workflow_test.go
pkg/tanka/prune.go
pkg/tanka/workflow.go

Closes https://github.com/grafana/tanka/issues/743 
Closes https://github.com/grafana/tanka/issues/693 
It replaces the `--dangerous-auto-approve` option. It has three values: `always`, `never` and `if-no-changes`
In this PR, I also create a common structure for args that are shared between `prune`, `delete` and `apply` Doing so, I found two bugs:
- Removed the `--validate` option on `delete`, it wasn't used
- Wired in `--dry-run` to the `prune` command, it was exposed but didn't make it to kubectl

Add new `--auto-approve=if-no-changes` option

---

.github/workflows/benchstat-pr.yml
pkg/jsonnet/imports_test.go

This will be used to compare performance in a future PR
I also added a workflow that posts a comparison of all benchmarks in the project. If we want to improve performance elsewhere, it'll be easier to do so. I will definitely need to do so on a feature I'm working on

Add benchmark function for getSnippetHash

---

pkg/jsonnet/imports.go

When calculating the env hash to use as cache keys, we don't need an exact list of imports 
Therefore, to improve performance, we can replace the current strategy of using the AST by a regexp strategy. 
This new strategy can lead to false positives (e.g. a string containing import 'foo') but this is not an issue for the hashing function. 
All that matters is that the hash is consistent and accounts for all files (no false negatives)
On actual huge real-life environments, I have seen improvements of up to 95% (from 2s to 100ms)

`getSnippetHash`: Use regexp instead of parsing whole AST

---

Makefile
cmd/tk/main.go
go.mod
go.sum
pkg/helm/charts_test.go
pkg/jsonnet/importer.go
pkg/jsonnet/jpath/dirs_test.go
pkg/jsonnet/lint.go
pkg/kubernetes/client/kubectl.go
pkg/kubernetes/kubernetes.go
pkg/process/data_test.go
pkg/process/filter.go
pkg/process/process_test.go
pkg/tanka/format.go
pkg/tanka/load_test.go

Just an initial go at fixing some minor code issues.
Some linters (like `revive`) will find lots of things so I'm starting with an initial basic run

Add `golangci-lint` with default linters

---

.drone/drone.jsonnet
.drone/drone.yml

grafana/tanka:${commit}
This will allow us to use Tanka faster without releasing, leading to less bugs in releases

Push commit hash docker image on pushes to main

---

cmd/tk/flags.go
cmd/tk/fmt.go
cmd/tk/init.go
cmd/tk/main.go
cmd/tk/tool.go
cmd/tk/toolCharts.go
cmd/tk/workflow.go
go.mod
go.sum
pkg/helm/charts.go
pkg/tanka/export.go
pkg/tanka/export_test.go
pkg/tanka/load.go
pkg/tanka/parallel.go
pkg/tanka/prune.go
pkg/tanka/static.go
pkg/tanka/workflow.go

Exposes a `--log-level` arg on every command
Replaces all `log` uses with either `fmt.Fprint(os.Stderr)` or zerolog calls
Benefits:
- We're currently mixing actual logs (that should have a level/are purely informational) and things that we want to print to stderr (possibly parsed by user). Using zerolog and fmt is more deliberate in meaning
- Logs can be disabled or turned on using the `--log-level` option
- We'll be able to add more verbose logs without potentially annoying people. An example is the "Loading environment" messages that the export command now prints. I shifted that to debug
- Will allow for trace level logs. Ex: https://github.com/grafana/tanka/issues/751, logs from the underlying `kubectl` exec or helm

Use `zerolog` instead of `log`

---

cmd/tk/lint.go
pkg/helm/charts.go
pkg/jsonnet/eval.go
pkg/jsonnet/lint.go
pkg/tanka/parallel.go

Follow-up to https://github.com/grafana/tanka/pull/766
- Shift linting name logging to debug logging. Instead of sending everything to stdout, we can now have a cleaner "report"
- Missed some `log.Printf`(alias for Debug) in helm code, shifted that to info logs
- Added some caching logs, whether or not it's a cache hit + time elasped to calculate hash
- Changed `time` for `duration_ms` in env loading log. This conflicts with the log time

Additional logging + improvements to logging

---

pkg/kubernetes/diff.go
pkg/kubernetes/kubernetes.go
pkg/kubernetes/util/diff.go
pkg/kubernetes/util/diff_test.go
pkg/kubernetes/util/testdata/added-and-removed.diff
pkg/kubernetes/util/testdata/added-and-removed.stat
pkg/kubernetes/util/testdata/changed-attributes.diff
pkg/kubernetes/util/testdata/changed-attributes.stat
pkg/kubernetes/util/testdata/changed-lots-of-attributes.diff
pkg/kubernetes/util/testdata/changed-lots-of-attributes.stat
pkg/kubernetes/util/testdata/empty.stat
pkg/tanka/workflow.go

Closes https://github.com/grafana/tanka/issues/767
I got nerd sniped... though it was pretty quick to implement
- `diffstat` is not available in the `apk` registry so we would have to compile it manually to add it to the docker image
- Parsing a diff to get the number of lines is pretty simple
- I tried a few external libraries but they didn't work right + less libs is better
So I opted to write our own implementation of diffstat (probably much simpler than the real thing, less cases to handle)

Replace external call to `diffstat` with native code

---

cmd/tk/main.go

This PR attempts to address a behaviour change that made it via https://github.com/grafana/tanka/pull/766
We were able to identify this issue at GrafanaLabs because we run Tanka in our CI pipelines and on errors, Tanka was still exiting with 0, executing the subsequent steps of the pipeline.

Exit with a non-zero status on cmd execution errors

---

cmd/tk/main.go

When an error occurs, it is ultimately brought to the `main.go` file where it is printed for the user (or machine) 
Using log.Fatal garbles the error by not rendering newlines
This reverts https://github.com/grafana/tanka/pull/774 but adds an os.Exit(1) which is an alternative fix to what the PR did

Revert to fmt.Print for error logging

---

pkg/jsonnet/find_importers.go
pkg/jsonnet/find_importers_test.go

I hadn't done it before because the benefit was minimal. 
However, I've found out that for very heavily used libraries (used by hundreds/thousands of files), it does help 
For example, for [`ksonnet-util`](https://github.com/grafana/jsonnet-libs/tree/master/ksonnet-util) which we use everywhere, compute time goes from ~13s to ~6s

`tk tool importers`: Cache the full result

---

cmd/tk/export.go

Just that, fixing a typo that I realised was there because I copy-pasted it from the console and was struggling to figure out why my tanka execution was failing :facepalm: . Let's try to avoid that to other users.

Fix typo on merge-strategy option's help

---

.github/workflows/publish-page.yml
docs/gatsby-config.js
docs/package.json
netlify.toml

This gets rid of netlify which we don't really need and is blocking PRs like https://github.com/grafana/tanka/pull/783 This contains two different parts:
- A step that deploys to a preview for PRs
- A step that deploys on a push to main
**NOTE: Netlify is failing on this PR as well, I will remove the Netlify webhook once this is deployed and I've validated it works**

Deploy website to Github Pages

---

cmd/tk/flags.go
cmd/tk/workflow.go
pkg/tanka/workflow.go

Closes #798
Introduce flag `--color` to control the colorization of diff output.
Add flag to all commands that can output colorized diff text:
- `diff`
- `apply`
- `prune`
`--color` has 3 allowed values:
- `auto` (default): colorize if stdout is a terminal (current behavior)
- `always`: always colorize output
- `never`: never colorize output
Example: `--color=always`
Example: `--color=never`

Support forcing color output on/off

---

CHANGELOG.md

It's tedious to create a changelog and push it to main, especially since Github releases can auto-generate decent changelogs from PRs. I propose to use Github releases from now on

Add notice to find changelogs in the Github release page

---

docs/docs/libraries/overriding.md

`jb init <dependency>` leads to:
```
Error parsing commandline arguments: unexpected github.com/grafana/loki/production/ksonnet/loki@v2.7.2
jb: error: unexpected github.com/grafana/loki/production/ksonnet/loki@v2.7.2
```

docs: update override method for tanka

---

pkg/process/extract.go
pkg/process/extract_test.go

I'm working in that area, and will modify more things. Setting up a benchmark before going further
Bench results from that small change in the extraction func:
From `go test -benchmem -run=^$ -bench ^BenchmarkExtract$ github.com/grafana/tanka/pkg/process -count=10`
```
name               old time/op    new time/op    delta
Extract/regular-8    16.6µs ±20%    14.7µs ±19%  -11.47%  (p=0.019 n=10+10)
Extract/flat-8       7.09µs ±16%    6.18µs ±12%  -12.81%  (p=0.001 n=9+10)
Extract/deep-8       39.6µs ±13%    34.9µs ±13%  -11.92%  (p=0.000 n=9+9)
Extract/array-8      54.0µs ±27%    46.0µs ±13%  -14.68%  (p=0.006 n=10+9)
Extract/nil-8        17.6µs ±24%    13.8µs ± 6%  -21.48%  (p=0.000 n=10+8)
name               old alloc/op   new alloc/op   delta
Extract/regular-8    2.35kB ± 0%    2.22kB ± …
```

Add benchmark for Extract + small speed improvement

---

pkg/process/data_test.go
pkg/process/extract.go
pkg/process/extract_test.go
pkg/process/testdata/tdBadKindType.jsonnet
pkg/process/testdata/tdMissingAttribute.jsonnet

Closes https://github.com/grafana/tanka/issues/817
This is something that comes up quite often in our internal environments 
When a data structure is not a Kubernetes manifest, the error makes it hard to find out why
This adds a reason, and context for why the object we found isn't a Kubernetes object 
In the issue linked above, the error was:
```
>> tk show environments/default
Error: got an error while extracting env `environments/default`: recursion did not resolve in a valid Kubernetes object.  In path `.grafana.deployment` found key `apiVersion` of type `string` instead.
```
It is now:
```
>> tk show environments/default
Error: got an error while extracting env `environments/default`: found invalid Kubernetes object (at .grafana.deployment): attribute "kind" is not a string, it is a …
```

Improved manifest extraction errors

---

cmd/tk/env.go
cmd/tk/main.go
cmd/tk/tool.go
cmd/tk/toolCharts.go

Fixes https://github.com/grafana/tanka/issues/810
`--log-level` should now be usable in every command, including `env`, `tool` and `tool charts`
Also added some consistency around the arg validation of root commands (`env`, `tool` and `charts`)

Add the `--log-level` option to nested commands

---

Dockerfile
go.mod

Switch the base images used for the Docker build to specify the golang version, so we know what we're building for and can trigger rebuilds when needed.

Bump to go 1.20

---

docs/docs/helm.mdx
pkg/helm/helm.go
pkg/helm/jsonnet.go
pkg/helm/jsonnet_test.go
pkg/helm/template.go

This is what `helm install` does. With Helm 3, we aren't installing CRDs by default any more and we expect this to be what most Tanka + Helm users want.
Closes: #829

helm: Set `includeCrds` to true by default

---

.drone/drone.jsonnet
.drone/drone.yml

This is useful to easily compare results when benchmarks are previously established in the main branch
I'm not sure yet if I want to post a PR message, it can be unnecessarily noisy in PRs that don't modify benchmarked stuff, so let's go without one for now

Run benchmark against main in PRs

---

.drone/drone.jsonnet
.drone/drone.yml
Makefile
cmd/tk/env.go
cmd/tk/jsonnet.go
cmd/tk/util.go
pkg/helm/charts.go
pkg/jsonnet/importer.go
pkg/kubernetes/client/apply.go
pkg/process/filter.go
pkg/tanka/inline.go
pkg/tanka/prune.go
pkg/tanka/static.go
pkg/tanka/workflow.go

- The go version was upgraded here: https://github.com/grafana/tanka/pull/836/files but not actually in the Drone config where Tanka is actually built
- Bump golangci-lint, it crashed with 1.20
- Fix new linting errors from new version
- Lock the `plugins/manifest` Drone plugin to v1.4.0. They broke the latest version

Build with Golang 1.20

---

pkg/jsonnet/find_importers.go
pkg/jsonnet/find_importers_test.go
pkg/jsonnet/testdata/findImporters/environments/vendor-override-in-env/main.jsonnet
pkg/jsonnet/testdata/findImporters/environments/vendor-override-in-env/vendor/vendor-override-in-env/main.libsonnet
pkg/jsonnet/testdata/findImporters/vendor/vendor-override-in-env/main.libsonnet

Currently, if a file is pulled from a local vendor overriding a global vendor, the global vendor will still show up as an imported file 
This fixes the issue by removing the global vendored lib as imported files when there exists a locally vendored file with the same name

`tool importers`: Local vendor should override global vendor

---

.github/workflows/publish-page.yml

Dependabot PRs are failing this check, giving a red X in the status that makes it hard to see whether they passed CI or not. Also, we want this to work for updates to the yarn stuff.
Then because we do that, we lose the default permissions for other types too. Specifically, the pr-preview-action needs to comment which is  `pull-requests: write`. So set that too.

publish-page: Give write permissions explicitly

---

docs/docs/helm.mdx
pkg/helm/charts.go
pkg/helm/charts_test.go
pkg/helm/helm.go
pkg/helm/spec.go

Closes https://github.com/grafana/tanka/issues/830 
To support OCI registries for Helm charts:
- we need to pass the full URL when pulling those charts
- versioning is not necessarily semver now
- the `repo update` cmd is a no-op for OCI packages but still necessary for Helm repositories

Helm: Support OCI

---

.drone/drone.jsonnet
.drone/drone.yml
cmd/tk/tool.go
pkg/jsonnet/find_importers.go
pkg/jsonnet/find_importers_test.go
pkg/jsonnet/testdata/findImporters/environments/lib-import-relative-to-env/README.md
pkg/jsonnet/testdata/findImporters/environments/lib-import-relative-to-env/file-to-import.libsonnet
pkg/jsonnet/testdata/findImporters/environments/lib-import-relative-to-env/folder1/folder2/main.jsonnet
pkg/jsonnet/testdata/findImporters/lib/imports-relative-to-env/main.libsonnet

Following some issues, it is safer to consider all files with an environment as being imported by that env 
The particular issue I'm fixing happens when a library uses a relative import (unresolvable by itself) but that resolves to an env file when evaluated in that context
Example:
- in `lib/my-lib/main.libsonnet`: `import my-file.libsonnet` but `my-file.libsonnet` doesn't exist in that lib
- in `env/myenv`: have `my-file.libsonnet` exist and `import "my-lib/main.libsonnet"`. This evaluates correctly because the lib import is found in the env
- The issue here is that if you run `tool importers env/myenv/my-file.libsonnet`, it will find nothing
I initially tried to do something smarter where I keep references of all imports that were made in files that are imported by each environment and …

`tool importers`: Fix case where environment-adjacent imports were not found

---

cmd/tk/tool.go
pkg/jsonnet/find_importers.go
pkg/jsonnet/find_importers_test.go
pkg/jsonnet/testdata/findImporters/environments/using-deleted-stuff/main.jsonnet

One of the issues we are facing with this command is whenever someone deletes a file and it's still being used somewhere:
- We can't pass this file to the `importers` command because it will fail trying to find symlinks
- Jsonnet main files which are using this file will not be found
- We end up with erroring projects that are only found out the next time they are evaluated
This PR adds support for deleted files via a `deleted:` prefix that can be added to files that were deleted. In that case, a simple filepath.Abs logic is used instead of trying to find symlinks and the same import resolution process happens as with existing files
Ex:
```console
tk tool importers deleted:lib/external-secrets/main.libsonnet
```

`tk tool importers`: Handle deleted files

---

docs/docs/helm.mdx

At GrafanaLabs we have been using this feature since its introduction in 2020. We consider this feature stable thus removing the experimental warning.

Helm: remove the experimental warning

---

cmd/tk/jsonnet.go
pkg/tanka/evaluators.go
pkg/tanka/evaluators_test.go

If the first level trying to eval has characters like `-` or `.` in them, it's currently impossible to eval 
With this PR, we can do `-e '["my-key"]'`

eval: Allow map key as expression

---

pkg/tanka/parallel.go

No need to launch 32 workers if we have two envs to export!

Clamp thread count to number of envs to export

---

docs/docs/inline-environments.mdx

Came across small typo when reading docs. I imagine this should read `as simple as` instead of `a simple as`.

inline-environments-doc: fix typo with `a` -> `as`

---

cmd/tk/export.go
cmd/tk/flags.go
cmd/tk/status.go
cmd/tk/workflow.go
pkg/jsonnet/eval.go
pkg/tanka/load.go
pkg/tanka/parallel.go
pkg/tanka/tanka.go

Since Iain's change (https://github.com/grafana/tanka/pull/914#discussion_r1304611891) to my PR, the JsonnetImplementation option is not used in the `jsonnet` package, so the `jsonnet` package doesn't need to know about it
This removes the option there and shift it up to the `tanka.Opts` struct which is where the jsonnet implementation to use is determined

Jsonnet: Move the `JsonnetImplentation` option upwards

---

.drone/drone.jsonnet
.drone/drone.yml
cmd/tk/flags.go
pkg/jsonnet/eval_test.go
pkg/jsonnet/implementations/binary/impl.go
pkg/tanka/load.go
pkg/tanka/load_test.go

_waiting for https://github.com/grafana/tanka/pull/917_
This allows users to specify `binary:<path>` as their jsonnet implementation.
When doing so, Tanka will evaluate jsonnet by invoking the given binary.

Jsonnet: Add binary jsonnet implementation

---

pkg/tanka/parallel.go

In the case of an export, the Jsonnet implementation set in specific environments should override the one set globally with the CLI args.
Currently, `o.JsonnetImplementation` is almost never empty since the default is `go`

Fix Jsonnet implementation override

---

pkg/kubernetes/client/context.go

Fixes #947 
Looks like the context and cluster names are not yet matched exactly within the ContextFromName function (and the cluster name is not matched exactly in other places). This PR changes that.
This only leads to mis-matches if there are name candidates where the expected name is a suffix of others and at least one of these is lexically sorted before the expected name:
```
expected: docker
candidates:
- docker
- abc-docker
- bcd-docker
match: abc-docker (because lexcially before docker and has expected name as substring)
```
vs.
```
expected: docker
candidates:
- docker
- test-docker
- dummy-docker
match: docker
```
I'm not sure if the endpoint in `IPFromContext` should also be matched exactly and so I didn't touch that one yet 🙂

fix(kubernetes-client): Match context & cluster names exactly

---

.github/workflows/docker.yml

This is an attempt to fix the docker workflow in combination with the recently released upload-artifact@4 and download-artifact@4 actions

ci: Support for upload/download-artifact@4 action

---

pkg/process/extract.go
pkg/tanka/export_test.go
pkg/tanka/testdata/test-export-envs-broken/static-env/main.jsonnet
pkg/tanka/testdata/test-export-envs-broken/static-env/spec.json

When there's an invalid Kubernetes object, we can get a `*manifest.SchemaError` here, for example. We currently panic, but instead we should return the error so it can be displayed properly.
Closes: #960

extract: Don't crash when the error is not an `ErrorPrimitiveReached`

---

.github/actions/setup-goversion/action.yml
.github/workflows/release.yml
.github/workflows/tests.yml

chore: Use Dockerfile as source for the Go version

---

.github/workflows/docker.yml

Added here: https://github.com/grafana/shared-workflows/pull/36

Github Actions: Use shared action to login to DockerHub

---

pkg/helm/jsonnet.go
pkg/helm/jsonnet_test.go

closes https://github.com/grafana/tanka/issues/906
Ran some tests with this caching enabled to compare to previous runs
```bash
$ time tk export --log-level debug ...
...
real    0m6.126s
user    0m37.292s
sys     0m6.492s
$ time ../../../go/src/github.com/grafana/tanka/tk export --log-level debug ...
...
real    0m5.034s
user    0m33.140s
sys     0m2.881s
```
To check once more I also tried with `--parallel 1` and the times were:
```bash
$ time tk export ...
real    0m17.966s
user    0m34.064s
sys     0m3.301s
$ time ../../../go/src/github.com/grafana/tanka/tk export ...
real    0m13.808s
user    0m30.874s
sys     0m1.721s
```
From the logs I can also verify the cache is being used
```
{"level":"debug","time":"2024-04-17T11:02:42-05:00","message":"Using cached template for flux2"}
```
I …

Cache helm templates for the same inputs

---

cmd/tk/toolCharts.go
pkg/helm/charts.go
pkg/helm/charts_test.go
pkg/helm/spec.go

Closes https://github.com/grafana/tanka/issues/922
Usage of private Helm repositories right now requires the credentials to be stored in the `chartfile.yaml`. This leads to issues described in the linked issue where different users usually have different credentials, and those credentials you probably don't want to commit to version control. Helm has a `repositories.yaml` file that is updated when you run `helm repo add` where it stores your user-supplied credentials to any private repository. This file has a similar layout to the repositories section in the `chartfile.yaml`
```yaml
apiVersion: ""
generated: "0001-01-01T00:00:00Z"
repositories:
- caFile: ""
certFile: ""
insecure_skip_tls_verify: false
keyFile: ""
name: simkev2
pass_credentials_all: false
password: <generated token>
url: …
```

Add repository config option for private repositories

---

cmd/tk/toolCharts.go
pkg/helm/charts.go
pkg/helm/charts_test.go
pkg/helm/helm.go
pkg/helm/jsonnet_test.go

This change is  a part of a larger effort to enable more automatic helm chart version management. First step is to get a command that can search the repositories within a `chartfile.yaml` for newer versions of the required charts. This output should be easy to parse for another script in order to kick off an automation to add the chart, vendor it, and make a PR.
Adding 2 different flux2 requires returns only 1 chart update :
```bash
$ ../../../../../go/src/github.com/grafana/tanka/tk tool charts version-check | jq
[
{
"name": "fluxcd-community/flux2",
"version": "2.12.4",
"app_version": "2.2.3",
"description": "A Helm chart for flux2"
}
]
```
**Potential question here, should we be searching the existing requires for this version and exclude it if so? Right now if you have versions 2.12.4 …

Add version-check command for vendored helm charts

---

cmd/tk/init.go

Hello 👋
It seems that support for Kubernetes versions 1.20 through 1.25 were recently removed from [k8s-libsonnet](https://github.com/jsonnet-libs/k8s-libsonnet) by this commit: jsonnet-libs/k8s-libsonnet@90d0fae415cff9d0c089d60e9a478efee092c42e. Since then, `tk init` (without the `--k8s` flag set) fails by default since the files for 1.20 are no longer available. See example below.
```bash
$ tk init
GET https://github.com/jsonnet-libs/k8s-libsonnet/archive/bf9a62cfd32a58c071b8410bfcdec058475dd25e.tar.gz 200
panic: rename /Users/root/project/vendor/.tmp/28d5d0cf4e0847d16afe3035627683a62705765237/1.20 /Users/root/project/vendor/github.com/jsonnet-libs/k8s-libsonnet/1.20: no such file or directory
[...]
Installing k.libsonnet: exit status 2
```
I've proposed updating the `defaultK8sVersion` …

Update default k8s version to 1.29

---

pkg/helm/helm.go

If you are using a registry within your `chartfile.yaml` that you do not have a cached version of it seems that `helm search repo` will not function as expected. To fix this we can run a `helm repo update` on the repository file that will be used while searching in order to ensure we get up-to-date information.

Run helm repo update before searching repos

---

.github/workflows/publish-page.yml

This is necessary in order to allow for the preview of #1025 to work.

Docs: Add .nojekyll file to output

---

cmd/tk/util.go
docs/src/content/docs/env-vars.md

Adds TANKA_PAGER environment variable. Takes precedence over PAGER. If unset, PAGER works as it did before.
Resolves #1028

feat(cli): TANKA_PAGER environment variable

---

cmd/tk/main.go
pkg/tanka/find.go

Suppress logs that I suspect we don't want to be printing by default:
Before:
_default `info` logging prints unimportant information on basic commands_
```
$ tk env list
{"level":"info","environments":5,"ms_to_find_jsonnet_files":20.682708,"ms_to_find_environments":1.767584,"time":"2024-06-05T16:01:40-04:00","message":"Found Tanka environments"}
NAME                                           NAMESPACE    SERVER
...
```
_logs cannot be suppressed in completer because there is no way to send it --log-level flag_
```
$ tk show <TAB>{"level":"debug","parallelism":12,"paths":1,"time":"2024-06-05T16:05:37-04:00","message":"Finding Tanka environments"}
{"level":"info","environments":5,"ms_to_find_jsonnet_files":20.73575,"ms_to_find_environments":2.033417,"time":"2024-06-05T16:05:37-04:00","messag …
```

don't print debug logs by default in `complete`, `env list`

---

docs/src/content/docs/tutorial/abstraction.md
docs/src/content/docs/tutorial/k-lib.mdx
docs/src/content/docs/tutorial/parameters.md

Still wip, i need to go through the content again.
I changed the "parameters" page to use functions and function parameters instead of a global config object, and reworked the following sections. I've also added a section at the end describing how to use a local config object to avoid some repetition but without the issues associated with having it as a global.
Fixes #816

docs: rework tutorial to not use global $

---

cmd/tk/fmt.go

Fix #942 
The issue is caused because the no changes output uses `Fprintln`, since the output when files are formatted wants to include the file number it uses `Fprintf` which requires a `\n` at the end to include the new line.

Add new line at the end of "Formatted %v files" output

---

pkg/kubernetes/client/diff.go
pkg/kubernetes/client/diff_test.go

Resolves https://github.com/grafana/tanka/issues/532
From what I can see this is the only place that actually does a typecheck for exec.ExitError. Because of that, wrapping the error should not be an issue.

fix: Do not hide diff error details (kubectl < 1.18.0)

---

.github/dependabot.yml

This should also finally discover outdated dependencies in these two folders.

chore: Add dependabot updates to dagger & acceptance-tests folders

---

.github/workflows/publish-page.yml

Resolves https://github.com/grafana/tanka/issues/1054

CI: Run publish-page workflow only on non-forks and docs changes

---

.github/actions/setup-goversion/action.yml
.github/workflows/acceptance-tests.yml
.github/workflows/check-dagger-drift.yml
.github/workflows/docker.yml
.github/workflows/publish-page.yml
.github/workflows/release.yml
.github/workflows/tests.yml

Closes https://github.com/grafana/tanka/issues/1045
Based on [best practices](https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions#using-third-party-actions), pin all 3rd party actions to a specific commit SHA

feat(actions): Pin commit SHAs

---

.github/workflows/lint-pr-title.yml

This should prevent PRs from getting merged that don't use convention commit messages as titles. Eventually, we might generate changelogs and release-versions out of this.
Until shared workflow actions have their own versioning, this will probably only be pinned to the main branch.

ci: lint PR titles

---

cmd/tk/env.go
cmd/tk/export.go

Using `std.extVar` in an inline environment's definition will cause `tk env list` and `tk export ... --recursive` to fail.
An example use case (what I'm writing this to support), is when you have inline environments whose namespace needs to be set at runtime, such as a review environment whos namespace is dynamic eg:
```jsonnet
{
prod: {
apiVersion: 'tanka.dev/v1alpha1',
kind: 'Environment',
metadata: {
name: 'prod',
},
spec: {
namespace: 'prod',
applyStrategy: 'server',
},
},
review: {
apiVersion: 'tanka.dev/v1alpha1',
kind: 'Environment',
metadata: {
name: 'review',
},
spec: {
namespace: std.extVar('reviewNamespace'),
applyStrategy: 'server',
},
}
}
```
Tanka has a bunch of different ways one could work around this, but its very convenient to be able to specify the default namespace so …

feat: allow using external variables in export and env list  

---

.github/workflows/release.yml

The `env` context does not contain all environment variables but just those that were explicitly set by writing to `$GITHUB_ENV` or through the `env` property of the step/job. Since that is not the case here, the variable is empty.
This switches over to using `${{ github.ref_name }}`.

ci: fix missing tag name in release draft

---

docs/src/content/docs/jsonnet/overview.md

This feature was removed in 2020: https://github.com/grafana/tanka/issues/135

docs: remove statement about importing YAML files

---

go.mod
go.sum
pkg/jsonnet/files.go

This removes an external dependency and hopefully also fixes #1055.
Performance-wise the two implementations look comparable:
Old:
```
goos: darwin
goarch: arm64
pkg: github.com/grafana/tanka/pkg/jsonnet
BenchmarkFindImporters-8               	      85	  12308651 ns/op
BenchmarkFindImporters_StaticCases/no_files-8         	  530050	      2272 ns/op
BenchmarkFindImporters_StaticCases/invalid_file-8     	   86710	     13794 ns/op
BenchmarkFindImporters_StaticCases/project_with_no_imports-8         	    3116	    386994 ns/op
BenchmarkFindImporters_StaticCases/local_import-8                    	    3112	    384138 ns/op
BenchmarkFindImporters_StaticCases/local_import_with_relative_path-8 	    3141	    382911 ns/op
BenchmarkFindImporters_StaticCases/lib_imported_through_chain-8      	    3099 …
```

fix: replace godirwalk with filepath.WalkDir

---

pkg/tanka/find.go

Fixes https://github.com/grafana/tanka/issues/1175
Unfortunately, this issue wasn't even visible with the `BenchmarkFindEnvsFromPaths` test running at more than 500 iterations. With running the env-list command with a new process every iteration, the error appeared after 30-120 runs. After applying this change, the error did not re-appear even after around 10K runs.

fix: prevent concurrent writes in `env list` command

---

README.md

Both lists are basically not used and so referencing that prominently does not make sense anymore.

docs: remove mailinglists from the README

---

.github/workflows/acceptance-tests.yml
.github/workflows/check-dagger-drift.yml
.github/workflows/docker.yml
.github/workflows/lint-pr-title.yml
.github/workflows/tests.yml

We often get several Dependabot pull requests in a short period. Our current repository settings - we require a successful build in CI, build for arm64, and require branches to be up to date - means it can be slow to manually merge them.
I'd like to switch to using merge queues, then we can disable the requirement for branches to be up to date before merging, since this will be handled by the queue. Developers will then be able to review and enqueue all the PRs, and they will be tested properly against the main branch.
To be able to do that we need to run the required tests for enqueued pull requests. That's what we're doing here.

feat(ci): run required checks on merge groups

---

.github/workflows/docker.yml

Emulated arm64 builds are slow. Fortunately, GitHub has real Linux ARM64 hardware these days, so let's switch to it.

feat(ci): run on real arm64 builders

---

catalog-info.yaml

This is used for internal project tracking.

chore: add catalog-info.yaml for project metadata

---

pkg/kubernetes/apply.go
pkg/process/process.go
pkg/process/process_test.go
pkg/spec/v1alpha1/environment.go
pkg/spec/v1alpha1/environment_test.go
pkg/spec/v1alpha1/reflect_utils.go

This change looks to add support for the environment label override from fields that #824 requested.
This allows users to alter the label themselves which allows a workaround of the issue described in #824.
As this is my first time contributing, I've not fully tidied this PR up yet as I want to get feedback from the maintainers on whether approach is sound/in-line with the vision of the codebase and if there's anything else I should bear in mind.

feat: add support for overriding environment label (#824)

---

.release-please.json

We want to avoid reaching 1.0.0 by accident 😄

ci: prevent breaking change from creating major release < 1.0.0

---

pkg/kubernetes/client/client.go
pkg/kubernetes/client/delete.go
pkg/kubernetes/client/delete_test.go
pkg/kubernetes/delete.go

If a resource has the kind "HiThere" but its singular is "hi-there" then deletion was not possible since Tanka operated on the kind and not the singular/plural defined in the CRD.
This changes the handling to following the `TYPE.VERSION.GROUP` format when possible.
Resolves https://github.com/grafana/tanka/issues/1229

fix: delete command supports kinds that do not match singular/plural names

---

cmd/tk/flags.go
cmd/tk/flags_test.go

Problem: If a string with a quote was passed to tk eval's --tla-str or --ext-str, things would break in an unexpected fashion.
Fix: Properly JSON-quote any given string.

fix: handle quotes in --tla-str and --ext-str in "tk eval"

---

.github/workflows/docker.yml
.github/workflows/release-please.yml

The docker workflow was not properly triggered by release-please and so we didn't get a 0.30.0 docker image. With this PR we will now call the docker workflow explicitly from release please.

ci: create release docker image through workflow-call

---

Dockerfile

Seems like the location changed around 1.31.0. The new location also includes the current patch release and thereby updating kubectl to 1.31.3.

chore: update location from where kubectl is downloaded from

---

acceptance-tests/flag_test.go
cmd/tk/env.go
cmd/tk/flags.go
cmd/tk/jsonnet.go

Right now this flag is defined in 3 places, with this change there should only be a single place for it.

refactor: define jsonnet-implementation flag in a single place

---

.github/renovate-config.json5
.github/workflows/acceptance-tests.yml
.github/workflows/docker.yml
.github/workflows/renovate.yml
Dockerfile
Makefile
dagger/dagger.gen.go
dagger/main.go

We need a way to update the dependencies mentioned inside the Dockerfile definition. Dependabot does not support this but Renovate does, allowing to treat arbitrary strings as version identifiers.
This also includes support for updating the kubectl, kustomize, and helm versions included in the Dockerfile.

ci: add renovate

---

.github/dependabot.yml

See https://github.com/grafana/tanka/pull/1272

ci: ignore Astro 5 for now as Starlight does not support it yet

---

cmd/tk/flags.go
cmd/tk/flags_test.go

Convert the flag values to `import/importstr @"verbatim ""quoted"" string"`,
pretty much like go-jsonnet does it.
Implements https://github.com/grafana/tanka/issues/848

feat: support --{tla,ext}-{code,str}-file flag in "tk eval"

---

.github/dependabot.yml

Reverts grafana/tanka#1274
A new version of Starlight is now available which no does not support Astro 4 anymore and so we can update both.

Revert "ci: ignore Astro 5 for now as Starlight does not support it yet"

---

.github/workflows/release-please.yml

This removes some unnecessary complexity in the workflow.

ci: use ncipollo/release-action for uploading release artifacts

---

pkg/tanka/evaluators.go
pkg/tanka/evaluators_test.go
pkg/tanka/testdata/cases/function-with-zero-params/main.jsonnet
pkg/tanka/testdata/cases/with-optional-tlas/main.jsonnet

Some parts of tanka behave inconsistently with standard jsonnet when using inline environments with top level arguments.  The differences can be illustrated by this inline environment:
```jsonnet
function(foo="bar", fizz='buzz') {
apiVersion: 'tanka.dev/v1alpha1',
kind: 'Environment',
// Other env stuff
}
```
And then running:
```bash
$ tk env list main.jsonnet
NAME    NAMESPACE    SERVER    
```
which finds no environments.  Similarly running:
```bash
$ tk export export-dir main.jsonnet --recursive
{"level":"info","parallelism":8,"envs":0,"time":"2024-11-29T13:28:23-07:00","message":"Reducing parallelism to match number of environments"}
```
will export no manifests.  For both commands, appending `--tla-code foo=1` will resolve the issue, listing the environment and exporting manifests. …

fix: mimic --tla-code behavior from jsonnet for functions in main.jsonnet in env discovery

---

.github/workflows/docker.yml

Pins action according to the [latest tag](https://github.com/grafana/shared-workflows/releases/tag/dockerhub-login-v1.0.1) in the `shared-workflows` repo.

chore: pin login-to-dockerhub action

---

docs/src/content/docs/helm.mdx

This behaviour was previously undocumented. See
https://github.com/grafana/tanka/issues/550 for more context.

docs: add note about Tanka deploying test resources

---

pkg/helm/charts.go
pkg/helm/charts_test.go

Currently, when I trying to add a repository and a chart with containing the special char `-` in the repo name, it fails:
```
tk tool charts add-repo cert-manager https://charts.jetstack.io
{"level":"info","time":"2025-02-28T08:51:19+01:00","message":"Skipping cert-manager: invalid name. cannot contain any special characters."}
Error: 1 Repo(s) were skipped. Please check above logs for details
```
```
tk tool charts add cert-manager/cert-manager@1.17.1
{"level":"info","time":"2025-02-28T08:52:03+01:00","message":"Adding 1 Charts ..."}
{"level":"info","time":"2025-02-28T08:52:03+01:00","message":"Skipping cert-manager/cert-manager@1.17.1: not of form 'repo/chart@version(:path)' where repo contains no special characters."}
Error: 1 Chart(s) were skipped. Please check above logs for details …
```

fix(helm): allow special char in chart repo name

---

docs/src/content/docs/tutorial/k-lib.mdx

Change deployment default name to match deployment naming in the following example. Also now matches the deployment name of the previous self created deployment.

docs: update docs to reduce confusion in tutorial

---

pkg/tanka/evaluators.go
pkg/tanka/inline.go

Peek sets `JsonnetOpts.EvalScript` however Load always overrides that, because of this the performance improvement gets lost completely. This is very visible when using a different jsonnet implementation (jrsonnet) as the Peek loads the environment completely (in go), the performance gain from generating the env with jrsonnet gets lost.
This PR abstracts the comment load logic into a separate method, which in turn gets called by Peek and Load. This PR also fixes the `MetadataSingleEnvEvalScript` as it was only filtering on full names, not partial matches.

fix(tanka/inline): ensure Peek only grabs metadata

---

.github/actions/setup-goversion/action.yml

[This PR](https://github.com/grafana/tanka/pull/1549) is failing due to the action that parses a wrong version of golang - 
```text
Run actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5
with:
go-version: 1.25.0@sha256
check-latest: false
token: ***
cache: true
```
The current PR fixes that issue by further splitting the produced string to ignore `@` and whatever comes after it.

fix(setup-goversion): fix string manipulation to exclude unwanted strings and chars

---

cmd/tk/workflow.go
docs/src/content/docs/env-vars.md

I use 'tk show' quite frequently from the cli, I (think I) know what I'm doing, I'd like to permanently allow the dangerous redirects.

feat: support `TANKA_DANGEROUS_ALLOW_REDIRECT` env variable
