- docs/design/tanka.md
This PR adds a design document outlining the problem tanka is trying to solve and the taken solution.
Discuss please :)
> doc: Design document

- .drone/docker-manifest.tmpl
- .drone/drone.jsonnet
- .drone/drone.yml
- .drone/release-note.md
- LICENSE
- Makefile
- cmd/tk/init.go
- cmd/tk/jsonnet.go
- cmd/tk/main.go
- cmd/tk/other.go
- cmd/tk/tool.go
- cmd/tk/workflow.go
- go.mod
- pkg/jsonnet/jsonnet.go
- pkg/kubernetes/kubernetes.go
- pkg/kubernetes/subsetdiff.go
Moves the repository from sh0rez to grafana, updates all old repo names
> chore: relocate to grafana

- pkg/kubernetes/kubectl.go
- pkg/kubernetes/kubernetes.go
> feat(kubernetes): add namespace to apply preamble

- pkg/kubernetes/kubernetes.go
> fix(kubernetes): correct diff type on 1.13

- cmd/tk/main.go
Closes https://github.com/sh0rez/tanka/issues/21
> fix: remove datetime from log

- pkg/kubernetes/kubernetes.go
Allows stable order in show and diff
Fixes #19
> fix(kubernetes): sort during reconcile

- cmd/tk/main.go
Signed-off-by: Tom Wilkie <tom.wilkie@gmail.com>
> Only print deprecated warnings in verbose mode.

- .github/issue_label_bot.yaml
- .github/stale.yml
Adds some handy bots to the repository to do some of the curating work
> chore: bots

- CHANGELOG.md
> chore(release): v0.3.0

- docs/design/tanka.md
While reading through the design doc, I thought I can as well fix
those on the way.
> Fix some trivial typos

- CHANGELOG.md
> chore(release): v0.4.0

- README.md
It is cool for users to know what is Promtail.
Signed-off-by: Xiang Dai <764524258@qq.com>
> Add link for Promtail

- cmd/tk/env.go
- cmd/tk/jsonnet.go
- cmd/tk/tool.go
- cmd/tk/workflow.go
> fix(cli): command usage guidelines

- docs/diff-strategy.md
- docs/known-issues.md
"Fixes" #99.
@sh0rez are there other places where this should documented, too?
> doc: diff problems with TCP/UDP ports

- pkg/jsonnet/importer.go
Many YAML files has multiple resources. Currently, `import .yaml` handles one resource of a file. With this PR, if YAML files have multiple resources, the `import .yaml` returns `[]Object`.
> feat(jsonnet): importing yaml streams

- CHANGELOG.md
Include #125 in a release (pretty late actually)
> chore(release): v0.6.1

- cmd/tk/init.go
Uses `jb` to install k.libsonnet and kausal.libsonnet during `tk init`.
Can be disable using `--k8s=false`
Fixes #52
> feat(cli): install k.libsonnet during init

- cmd/tk/init.go
Cleaning up the mess of #140, whatever we have done there (import cycle lol)
> fix(cli): correct k.libsonnet import path in init

- cmd/tk/init.go
> Fix simple typo

- pkg/kubernetes/manifest/manifest.go
List objects don't always have metadata .. thus we cannot expect it.
See https://github.com/grafana/tanka/issues/113#issuecomment-572373821 by @anarcher for more details
> fix(kubernetes): don't require `metadata` on `.*List` objects

- docs/docs/jsonnet/main.md
This won't happen, because it actually makes no sense: https://github.com/grafana/tanka/issues/113#issuecomment-572649190
> docs(jsonnet): remove notice about metadata.name

- docs/docs/tutorial/jsonnet.mdx
> Fixed typo. Kubebernetes -> Kubernetes

- docs/docs/known-issues.md
jb version v0.2.0 only allows installing directories. See https://github.com/jsonnet-bundler/jsonnet-bundler/issues/43 and https://github.com/jsonnet-bundler/jsonnet-bundler/issues/66
> jsonnet-bundler doesn't allow file-level installs

- docs/docs/tutorial/refresher.mdx
Local port comes first, remote port second.
> Fix order of port args to port-forward

- docs/docs/tutorial/abstraction.mdx
Follow up to 855eeb1d83c4628a34ef8fdcbe671a68c1c21888, copy paste issue
Fixes #157
> fix(docs): s/port/name

- docs/docs/faq.md
- docs/docs/installation.md
- docs/docs/jsonnet/overview.md
- docs/docs/tutorial/jsonnet.mdx
- docs/docs/tutorial/k-lib.mdx
- docs/docs/tutorial/refresher.mdx
Fix/update the tanka docs.
Signed-off-by: Milan Plzik <milan.plzik@grafana.com>
> Update tanka docs.

- .drone/drone.yml
- .drone/release-note.md
> fix(docs): releaseNote sh0rez -> grafana

- docs/docs/tutorial/environments.mdx
> Fixed small typo

- cmd/tk/env.go
> fix(cli): server from context on env add

- docs/docs/tutorial/abstraction.mdx
grafana.libsonnet changed to grafana.jsonnet
> style(docs): filename typo in abstraction.mdx

- go.mod
- go.sum
Bumps to latest master version, has some neat improvements and we are
feeling lucky here :D
> feat: bump jsonnet to v0.14.1+master

- pkg/tanka/workflow.go
> fix(cli): show diff on apply instead of it's pointer

- CHANGELOG.md
> doc(release): Changelog for 0.8.0

- docs/docs/jsonnet/native-functions.md
This page is aimed at users new to Tanka or Jsonnet so it tries not to assume more knowledge than explained in the previous Jsonnet docs.
Documents:
- what a native function is
- how to use native functions in Jsonnet code
- usage and examples of Tanka native functions
> Update Native Functions documentation

- examples/prom-grafana/jsonnetfile.json
- examples/prom-grafana/jsonnetfile.lock.json
Were installed using a development version of jb that apparently never
worked at all
> fix(examples): prom-grafana dependencies

- docs/docs/config.md
The original line doesn't seem to work for me.
> Update environment import example

- cmd/tk/init.go
- docs/docs/env-vars.md
Fix #271,
@sh0rez let me know if this works for you.
> Fix jsonnet-bundler binary environment variable

- GOVERNANCE.md
- MAINTAINERS.md
Signed-off-by: Richard Hartmann <richih@richih.org>
> Give Tanka a governance

- docs/docs/tutorial/jsonnet.mdx
Clarify "include it in Jsonnet" to indicate where
> clarify "include it in Jsonnet"

- pkg/helm/charts.go
Need to change the regexp to also allow including chars like `-`
> fix(tool/charts): \w+ -> .+

- docs/docs/formatting.md
> Adds `tk fmt` documentation

- Dockerfile
Allows pulling secret jsonnet resources (stored in git); fixes #428
Signed-off-by: Matthias Riegler <matthias.riegler@taotesting.com>
> Added openssh-client to docker image

- docs/docs/helm.mdx
- docs/docs/kustomize.mdx
- docs/doczrc.js
- pkg/kustomize/jsonnet.go
> docs(jsonnet): add kustomize and update helm

- docs/docs/inline-environments.mdx
> docs(k8s): inline environments

- cmd/tk/env.go
- cmd/tk/init.go
- cmd/tk/util.go
initialize inline environments with `tk env add --inline` and `tk init --inline`
> feat(cli): initialize inline environments

- cmd/tk/prefix.go
> fix(cli): initialize executables map

- CHANGELOG.md
Changelog for this magnificent release and updates to the relevant docs.
> chore(release): Changelog for 0.14 stable

- ADOPTERS.md
Discussed with @malcolmholmes on grafana slack
> Add Yelp to ADOPTERS.md

- docs/docs/libraries/overriding.md
I found this doc very useful though spotted a couple of small typos that I've fixed.
> Fix typos in overriding.md

- cmd/tk/status.go
Implements ideas discussed on #474, @sh0rez feel free to merge this in there or cherry pick the commits.
> feat(cli): tk status improvements

- CHANGELOG.md
> chore(release): Changelog for 0.15 stable

- .drone/drone.jsonnet
- .drone/drone.yml
- .drone/vault.libsonnet
- CHANGELOG.md
Also get all secrets from Vault instead of using repository secrets
> Add v0.15.1 changelog

- CHANGELOG.md
With the docs being updated, we also should cut a new release to reflect this.
> chore(release): Changelog for 0.16 stable

- CHANGELOG.md
> chore(release): Changelog for 0.17 stable

- docs/docs/jsonnet/overview.md
Update to the tanka docs. 
See related thread
https://raintank-corp.slack.com/archives/CM666K5B7/p1627626121000100?thread_ts=1627599929.067100&cid=CM666K5B7
> Replacing "+::" with "+:".

- Dockerfile
I'd like to use Kustomize in the Tanka image.
Drone build on `docker` branch: https://drone.grafana.net/grafana/tanka/954/2/2
> feat(docker): add kustomize binary

- .drone/drone.jsonnet
- .drone/drone.yml
- Dockerfile
The arm 32 docker image doesn't seem used much and kustomize is not even available for
that. We can try to bring it back later on.
> feat(docker): fix build and remove arm 32 bit

- CHANGELOG.md
> chore(release): Changelog for 0.17.3

- cmd/tk/prefix.go
Under WSL this gets the time to start up tk down dramatically.
Before (v0.17.2):
```
$ time tk
Error: tanka <3 jsonnet
Usage:
tk [command]
[...]
real    0m7.766s
user    0m0.421s
sys     0m1.443s
```
With this change:
```
$ time ./tk
Error: tanka <3 jsonnet
Usage:
tk [command]
[...]
real    0m0.113s
user    0m0.012s
sys     0m0.019s
```
> check prefix before calling stat

- pkg/tanka/load.go
- pkg/tanka/load_test.go
- pkg/tanka/testdata/cases/static_and_inline/main.jsonnet
- pkg/tanka/testdata/cases/static_and_inline/spec.json
Fixes https://github.com/grafana/tanka/issues/612
> Add check for using spec.json and inline envs simultaneously

- cmd/tk/toolCharts.go
- pkg/helm/charts.go
- pkg/helm/charts_test.go
Supersedes https://github.com/grafana/tanka/pull/640 (adding unit tests)
> match Add() and AddRepos() and correct typos

- GOVERNANCE.md
- docs/docs/namespaces.md
- docs/doczrc.js
Should be `main`, not `master`
Closes https://github.com/grafana/tanka/issues/676
> Fix docs edit branch: `master` -> `main`

- .drone/drone.jsonnet
- .drone/drone.yml
- CHANGELOG.md
- Makefile
Adds support for Apple Silicon aka arm64.
> Add Apple Silicon binary

- cmd/tk/workflow.go
- pkg/kubernetes/client/apply.go
- pkg/kubernetes/client/apply_test.go
- pkg/kubernetes/client/client.go
- pkg/tanka/workflow.go
Fixes #694.
Support `tk apply --server-side ...`, passed down to `kubectl apply --server-side ...`.
> feat: support apply --server-side

- docs/docs/env-vars.md
Wasn't sure where to put it, I don't think it deserves its own section
This is probably enough, right? Searching for "pager" in the searchbox will find it
Closes https://github.com/grafana/tanka/issues/633
> Document the PAGER environment variable

- cmd/tk/init.go
fixes https://github.com/grafana/tanka/issues/723
> install docsonnet on `tk init` to make linting work

- go.mod
- go.sum
- pkg/tanka/evaluators.go
Updated go.mod and ran `go mod tidy`.
ref: https://github.com/google/jsonnet/releases/tag/v0.19.0
> chore(jsonnet): update to 0.19.1

- pkg/kubernetes/client/resources.go
- pkg/kubernetes/client/resources_test.go
Fixes https://github.com/grafana/tanka/issues/795.
> Update resources.go to take output from kubectl@1.26

- cmd/tk/env.go
- cmd/tk/tool.go
> Fix panic on tool / env sub-command

- .github/workflows/publish-page.yml
Some weird JS error, maybe fixed by using a fixed Node version
> Fix Github pages publishing action

- pkg/jsonnet/find_importers_test.go
I have to make some changes around these parts. This will help with making sure I don't destroy performance
> Benchmark all the regular cases for the `find-importers` command

- docs/gatsby-config.js
- docs/package.json
- docs/yarn.lock
> Remove netlify docs plugin

- docs/docs/kustomize.mdx
> fix kustomize docs

- docs/docs/tutorial/refresher.mdx
This may have changed in grafana, but it was Connections instead of Configuration when I just ran through this tutorial
> Update refresher.mdx for typo

- pkg/kubernetes/manifest/manifest.go
- pkg/process/sort.go
- pkg/process/sort_test.go
> fix: Use generateName as last comparison when sorting

- pkg/kubernetes/client/diff.go
Partial fix for [#1150](https://github.com/grafana/tanka/issues/1150)
> fix: remove unnecessary print statement

- .github/workflows/release-please.yml
> fix: `Unexpected input(s) 'github-token'` in `release-please` job

- acceptance-tests/export_test.go
Related to https://github.com/grafana/tanka/issues/1336
> test: add acceptance test for tk export -l

- docs/src/content/docs/tutorial/k-lib.mdx
> docs: fix k-lib usage
